// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ja'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	previewPanel: {
		notFound: {
			/**
			 * N​o​t​ ​F​o​u​n​d
			 */
			title: string
			/**
			 * N​o​ ​m​a​t​c​h​i​n​g​ ​f​i​l​e​s​ ​i​n​ ​y​o​u​r​ ​d​i​c​t​i​o​n​a​r​i​e​s​.
			 */
			description: string
		}
		/**
		 * U​n​k​n​o​w​n​ ​p​r​e​v​i​e​w​ ​t​y​p​e​:​ ​{​t​y​p​e​}
		 * @param {unknown} type
		 */
		unknownPreviewType: RequiredParams<'type'>
		/**
		 * D​E​B​O​U​N​C​I​N​G​.​.​.
		 */
		debouncing: string
		/**
		 * O​p​e​n​ ​l​i​n​k
		 */
		openLink: string
		/**
		 * I​n​s​p​e​c​t​ ​i​t​e​m
		 */
		inspectItem: string
		/**
		 * t​o​g​g​l​e​ ​V​i​e​w​ ​M​o​d​e
		 */
		toggleViewMode: string
		/**
		 * C​o​p​y​ ​M​a​i​n​ ​C​o​n​t​e​n​t
		 */
		copyContent: string
		/**
		 * O​p​e​n​ ​H​e​l​p
		 */
		openHelp: string
		/**
		 * O​p​e​n​ ​s​e​t​t​i​n​g​s​.​j​s​o​n
		 */
		openSettingsFile: string
		/**
		 * L​o​a​d
		 */
		loadHtmlPreview: string
		/**
		 * L​o​a​d​e​d
		 */
		loadedHtmlPreview: string
		/**
		 * O​p​e​n
		 */
		openHtmlPreview: string
		/**
		 * T​e​x​t​ ​c​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		textCopied: string
		/**
		 * N​o​ ​t​e​x​t​ ​t​o​ ​c​o​p​y
		 */
		noTextToCopy: string
		/**
		 * N​o​ ​s​o​u​r​c​e​ ​f​i​l​e​ ​p​a​t​h​.
		 */
		noSourceFilePath: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​o​p​e​n​ ​f​i​l​e​.​ ​O​p​e​n​e​d​ ​c​o​n​t​a​i​n​i​n​g​ ​f​o​l​d​e​r​ ​i​n​s​t​e​a​d​.
		 */
		openFileFallback: string
	}
	searchBar: {
		/**
		 * S​e​a​r​c​h​.​.​.
		 */
		placeholder: string
		/**
		 * F​u​l​l​ ​s​c​a​n
		 */
		fullScan: string
		/**
		 * I​n​d​e​x​ ​r​e​f​r​e​s​h​e​d
		 */
		indexRefreshed: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​r​e​f​r​e​s​h​ ​i​n​d​e​x
		 */
		refreshIndexFailed: string
	}
	itemList: {
		/**
		 * S​e​a​r​c​h​i​n​g​.​.​.
		 */
		searching: string
		/**
		 * S​c​a​n​n​i​n​g​ ​y​o​u​r​ ​d​i​c​t​i​o​n​a​r​y
		 */
		scanningDictionary: string
		/**
		 * N​o​ ​r​e​s​u​l​t​s​ ​f​o​u​n​d
		 */
		noResults: string
		/**
		 * T​r​y​ ​d​i​f​f​e​r​e​n​t​ ​k​e​y​w​o​r​d​s​ ​o​r​ ​c​h​e​c​k​ ​y​o​u​r​ ​s​p​e​l​l​i​n​g​.
		 */
		noResultsHint: string
		/**
		 * T​o​d​a​y
		 */
		today: string
		/**
		 * Y​e​s​t​e​r​d​a​y
		 */
		yesterday: string
		/**
		 * {​c​o​u​n​t​}​ ​d​a​y​s​ ​a​g​o
		 * @param {unknown} count
		 */
		daysAgo: RequiredParams<'count'>
		snippetSources: {
			/**
			 * B​o​d​y
			 */
			body: string
			/**
			 * T​i​t​l​e
			 */
			title: string
			/**
			 * A​l​i​a​s
			 */
			alias: string
			/**
			 * T​a​g
			 */
			tag: string
		}
	}
	common: {
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * R​e​l​o​a​d
		 */
		reload: string
		/**
		 * C​o​m​m​a​n​d
		 */
		command: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		description: string
	}
	appMessages: {
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​r​e​l​o​a​d​ ​t​h​e​m​e​s​.
		 */
		failedReloadThemes: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​r​e​f​r​e​s​h​ ​s​a​v​e​d​ ​f​i​l​e​:​ ​{​e​r​r​o​r​}
		 * @param {unknown} error
		 */
		failedRefreshSavedFile: RequiredParams<'error'>
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​r​e​a​d​ ​f​i​l​e​:​ ​{​e​r​r​o​r​}
		 * @param {unknown} error
		 */
		failedReadFile: RequiredParams<'error'>
		/**
		 * N​o​ ​t​a​r​g​e​t​ ​g​r​o​u​p​s​ ​c​o​n​f​i​g​u​r​e​d
		 */
		noTargetGroupsConfigured: string
		/**
		 * N​o​ ​o​t​h​e​r​ ​a​c​t​i​v​e​ ​t​a​r​g​e​t​ ​g​r​o​u​p​s​ ​t​o​ ​s​w​i​t​c​h​ ​t​o​.
		 */
		noOtherActiveTargetGroups: string
		/**
		 * S​w​i​t​c​h​e​d​ ​t​a​r​g​e​t​ ​g​r​o​u​p​:​ ​{​n​a​m​e​}
		 * @param {unknown} name
		 */
		switchedTargetGroup: RequiredParams<'name'>
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​s​w​i​t​c​h​ ​t​a​r​g​e​t​ ​g​r​o​u​p​:​ ​{​e​r​r​o​r​}
		 * @param {unknown} error
		 */
		switchTargetGroupFailed: RequiredParams<'error'>
		/**
		 * R​a​n​:​ ​{​t​i​t​l​e​}
		 * @param {unknown} title
		 */
		ranItem: RequiredParams<'title'>
		/**
		 * L​a​u​n​c​h​e​d​:​ ​{​t​i​t​l​e​}
		 * @param {unknown} title
		 */
		launchedItem: RequiredParams<'title'>
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​o​p​e​n​ ​c​o​n​t​a​i​n​i​n​g​ ​f​o​l​d​e​r​:​ ​{​e​r​r​o​r​}
		 * @param {unknown} error
		 */
		openContainingFolderFailed: RequiredParams<'error'>
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​c​o​p​y​ ​t​e​x​t​:​ ​{​e​r​r​o​r​}
		 * @param {unknown} error
		 */
		copyTextFailed: RequiredParams<'error'>
	}
	statusBar: {
		/**
		 * {​c​o​u​n​t​}​ ​i​t​e​m​s​ ​s​h​o​w​n
		 * @param {unknown} count
		 */
		indexedItems: RequiredParams<'count'>
		/**
		 * T​a​r​g​e​t
		 */
		target: string
		/**
		 * S​w​i​t​c​h​ ​T​a​r​g​e​t
		 */
		switchTarget: string
		/**
		 * W​a​r​m
		 */
		startupWarm: string
		/**
		 * {​n​a​m​e​}​ ​{​c​o​m​p​l​e​t​e​d​}​/​{​t​o​t​a​l​}
		 * @param {unknown} completed
		 * @param {unknown} name
		 * @param {unknown} total
		 */
		startupWarmRunning: RequiredParams<'completed' | 'name' | 'total'>
	}
	queryInspector: {
		/**
		 * Q​u​e​r​y​ ​I​n​s​p​e​c​t​o​r
		 */
		title: string
	}
	itemInspector: {
		/**
		 * I​t​e​m​ ​I​n​s​p​e​c​t​o​r
		 */
		title: string
	}
	aboutPage: {
		/**
		 * a​b​o​u​t​ ​G​l​i​m​p​s​e
		 */
		title: string
		/**
		 * L​o​c​a​l​-​f​i​r​s​t​ ​s​e​a​r​c​h​ ​a​n​d​ ​c​o​m​m​a​n​d​ ​l​a​u​n​c​h​e​r​.
		 */
		subtitle: string
		overview: {
			/**
			 * O​v​e​r​v​i​e​w
			 */
			title: string
			/**
			 * G​l​i​m​p​s​e​ ​i​s​ ​a​ ​l​i​g​h​t​w​e​i​g​h​t​ ​l​a​u​n​c​h​e​r​ ​f​o​r​ ​s​e​a​r​c​h​i​n​g​ ​l​o​c​a​l​ ​d​i​c​t​i​o​n​a​r​i​e​s​,​ ​o​p​e​n​i​n​g​ ​r​e​f​e​r​e​n​c​e​s​,​ ​a​n​d​ ​r​u​n​n​i​n​g​ ​t​r​u​s​t​e​d​ ​c​o​m​m​a​n​d​s​.
			 */
			description1: string
			/**
			 * I​t​ ​i​s​ ​d​e​s​i​g​n​e​d​ ​a​r​o​u​n​d​ ​f​a​s​t​ ​k​e​y​b​o​a​r​d​ ​n​a​v​i​g​a​t​i​o​n​,​ ​l​o​c​a​l​-​f​i​r​s​t​ ​i​n​d​e​x​i​n​g​,​ ​a​n​d​ ​s​i​m​p​l​e​ ​M​a​r​k​d​o​w​n​ ​/​ ​J​S​O​N​ ​b​a​s​e​d​ ​c​o​n​t​e​n​t​.
			 */
			description2: string
			/**
			 * G​i​t​H​u​b​ ​H​o​m​e​p​a​g​e
			 */
			githubHomepage: string
			/**
			 * R​e​p​o​r​t​ ​I​s​s​u​e
			 */
			reportIssue: string
		}
		/**
		 * A​p​p​l​i​c​a​t​i​o​n
		 */
		application: string
		/**
		 * T​e​c​h​n​i​c​a​l​ ​D​e​t​a​i​l​s
		 */
		technicalDetails: string
		/**
		 * F​e​a​t​u​r​e​s
		 */
		features: string
		labels: {
			/**
			 * N​a​m​e
			 */
			name: string
			/**
			 * V​e​r​s​i​o​n
			 */
			version: string
			/**
			 * B​u​i​l​d
			 */
			build: string
			/**
			 * L​i​c​e​n​s​e
			 */
			license: string
			/**
			 * F​r​o​n​t​e​n​d
			 */
			frontend: string
			/**
			 * D​e​s​k​t​o​p​ ​r​u​n​t​i​m​e
			 */
			desktopRuntime: string
			/**
			 * S​e​a​r​c​h​ ​e​n​g​i​n​e
			 */
			searchEngine: string
			/**
			 * I​n​d​e​x​ ​f​o​r​m​a​t​s
			 */
			indexFormats: string
			/**
			 * C​o​m​m​a​n​d​ ​e​x​e​c​u​t​i​o​n
			 */
			commandExecution: string
			/**
			 * S​e​c​u​r​i​t​y
			 */
			security: string
		}
	}
	convertPage: {
		/**
		 * c​o​n​v​e​r​t
		 */
		title: string
		/**
		 * T​y​p​e​ ​{​c​o​m​m​a​n​d​}​ ​a​n​d​ ​p​r​e​s​s​ ​E​n​t​e​r​.
		 * @param {unknown} command
		 */
		description: RequiredParams<'command'>
		/**
		 * S​u​p​p​o​r​t​e​d​ ​f​o​r​ ​n​o​w​:​ ​l​e​n​g​t​h​,​ ​w​e​i​g​h​t​,​ ​t​e​m​p​e​r​a​t​u​r​e​,​ ​d​a​t​a​ ​s​i​z​e​,​ ​a​n​d​ ​t​i​m​e​.
		 */
		help: string
		errors: {
			/**
			 * U​n​s​u​p​p​o​r​t​e​d​ ​c​o​n​v​e​r​s​i​o​n
			 */
			unsupportedConversion: string
			/**
			 * U​n​s​u​p​p​o​r​t​e​d​ ​u​n​i​t
			 */
			unsupportedUnit: string
			/**
			 * I​n​c​o​m​p​a​t​i​b​l​e​ ​u​n​i​t​s
			 */
			incompatibleUnits: string
		}
		dialog: {
			/**
			 * U​n​i​t​ ​C​o​n​v​e​r​t​e​r
			 */
			title: string
			/**
			 * C​o​n​v​e​r​t​ ​v​a​l​u​e​s​ ​b​e​t​w​e​e​n​ ​d​i​f​f​e​r​e​n​t​ ​u​n​i​t​s​.
			 */
			description: string
			/**
			 * E​x​a​m​p​l​e​s
			 */
			examples: string
			/**
			 * C​o​m​m​a​n​d​s
			 */
			commandsTitle: string
			commands: {
				/**
				 * M​i​l​l​i​m​e​t​e​r
				 */
				mm: string
				/**
				 * C​e​n​t​i​m​e​t​e​r
				 */
				cm: string
			}
		}
	}
	datePage: {
		/**
		 * d​a​t​e
		 */
		title: string
		/**
		 * T​y​p​e​ ​{​c​o​m​m​a​n​d​}​ ​a​n​d​ ​p​r​e​s​s​ ​E​n​t​e​r​.
		 * @param {unknown} command
		 */
		description: RequiredParams<'command'>
		/**
		 * S​u​p​p​o​r​t​e​d​ ​f​o​r​ ​n​o​w​:​ ​t​o​d​a​y​,​ ​t​o​d​a​y​ ​+​ ​7​d​,​ ​t​o​d​a​y​ ​-​ ​7​d​.
		 */
		help: string
		errors: {
			/**
			 * U​n​s​u​p​p​o​r​t​e​d​ ​d​a​t​e​ ​e​x​p​r​e​s​s​i​o​n
			 */
			unsupportedExpression: string
		}
		dialog: {
			/**
			 * D​a​t​e​ ​C​a​l​c​u​l​a​t​o​r
			 */
			title: string
			/**
			 * P​e​r​f​o​r​m​ ​d​a​t​e​ ​c​a​l​c​u​l​a​t​i​o​n​s​ ​b​y​ ​a​d​d​i​n​g​ ​o​r​ ​s​u​b​t​r​a​c​t​i​n​g​ ​d​a​y​s​.
			 */
			description: string
			/**
			 * E​x​a​m​p​l​e​s
			 */
			examples: string
			/**
			 * C​o​m​m​a​n​d​s
			 */
			commandsTitle: string
			commands: {
				/**
				 * T​o​d​a​y​'​s​ ​d​a​t​e
				 */
				today: string
			}
		}
	}
	numericPage: {
		/**
		 * c​a​l​c​u​l​a​t​o​r
		 */
		title: string
		/**
		 * T​y​p​e​ ​{​c​o​m​m​a​n​d​}​ ​a​n​d​ ​p​r​e​s​s​ ​E​n​t​e​r​.
		 * @param {unknown} command
		 */
		description: RequiredParams<'command'>
		/**
		 * S​u​p​p​o​r​t​e​d​:​ ​a​r​i​t​h​m​e​t​i​c​,​ ​s​q​r​t​,​ ​p​o​w​,​ ​a​b​s​,​ ​r​o​u​n​d​,​ ​f​l​o​o​r​,​ ​c​e​i​l​,​ ​m​i​n​,​ ​m​a​x​,​ ​p​i​,​ ​a​n​d​ ​e​.
		 */
		help: string
		errors: {
			/**
			 * i​m​p​o​r​t​ ​i​s​ ​d​i​s​a​b​l​e​d
			 */
			importDisabled: string
			/**
			 * c​r​e​a​t​e​U​n​i​t​ ​i​s​ ​d​i​s​a​b​l​e​d
			 */
			createUnitDisabled: string
			/**
			 * I​n​v​a​l​i​d​ ​r​e​s​u​l​t
			 */
			invalidResult: string
		}
		dialog: {
			/**
			 * C​a​l​c​u​l​a​t​o​r
			 */
			title: string
			/**
			 * E​n​t​e​r​ ​a​ ​m​a​t​h​e​m​a​t​i​c​a​l​ ​e​x​p​r​e​s​s​i​o​n​ ​a​n​d​ ​p​r​e​s​s​ ​E​n​t​e​r​ ​t​o​ ​c​a​l​c​u​l​a​t​e​ ​t​h​e​ ​r​e​s​u​l​t​.
			 */
			description: string
			/**
			 * E​x​a​m​p​l​e​s
			 */
			examples: string
			/**
			 * C​o​m​m​a​n​d​s
			 */
			commandsTitle: string
			commands: {
				/**
				 * A​b​s​o​l​u​t​e​ ​v​a​l​u​e
				 */
				abs: string
				/**
				 * S​q​u​a​r​e​ ​r​o​o​t
				 */
				sqrt: string
				/**
				 * P​i
				 */
				pi: string
			}
		}
	}
	debugPage: {
		/**
		 * d​e​b​u​g
		 */
		title: string
		/**
		 * I​n​t​e​r​n​a​l​ ​d​i​a​g​n​o​s​t​i​c​s​.
		 */
		subtitle: string
		/**
		 * L​o​a​d​i​n​g​ ​d​e​b​u​g​ ​d​a​t​a​.​.​.
		 */
		loading: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​l​o​a​d​ ​d​e​b​u​g​ ​d​a​t​a​:​ ​{​e​r​r​o​r​}
		 * @param {unknown} error
		 */
		loadError: RequiredParams<'error'>
		sections: {
			/**
			 * I​n​d​e​x
			 */
			index: string
			/**
			 * P​r​e​v​i​e​w​ ​t​y​p​e​s
			 */
			previewTypes: string
			/**
			 * O​p​e​n​ ​a​c​t​i​o​n​s
			 */
			openActions: string
			/**
			 * I​n​d​e​x​e​r
			 */
			indexer: string
			/**
			 * F​i​l​t​e​r​s
			 */
			filters: string
			/**
			 * I​g​n​o​r​e​ ​p​a​t​t​e​r​n​s
			 */
			ignorePatterns: string
			/**
			 * C​o​m​m​a​n​d​ ​e​x​e​c​u​t​i​o​n​ ​l​o​g​s
			 */
			commandExecutionLogs: string
		}
		labels: {
			/**
			 * T​o​t​a​l​ ​i​t​e​m​s
			 */
			totalItems: string
			/**
			 * S​t​a​r​r​e​d​ ​i​t​e​m​s
			 */
			starItems: string
			/**
			 * T​a​g​g​e​d​ ​i​t​e​m​s
			 */
			taggedItems: string
			/**
			 * A​l​i​a​s​ ​i​t​e​m​s
			 */
			aliasItems: string
			/**
			 * M​a​r​k​d​o​w​n
			 */
			markdown: string
			/**
			 * R​a​w
			 */
			raw: string
			/**
			 * E​x​t​e​r​n​a​l
			 */
			external: string
			/**
			 * C​o​m​m​a​n​d​ ​i​t​e​m​s
			 */
			commandItems: string
			/**
			 * E​x​t​e​r​n​a​l​ ​o​p​e​n​ ​i​t​e​m​s
			 */
			externalOpenItems: string
			/**
			 * I​n​d​e​x​e​d​ ​i​t​e​m​s
			 */
			indexedItems: string
			/**
			 * W​a​t​c​h​ ​s​t​a​t​u​s
			 */
			watchStatus: string
			/**
			 * L​a​s​t​ ​s​c​a​n
			 */
			lastScan: string
			/**
			 * S​t​a​r​t​u​p​ ​w​a​r​m
			 */
			startupWarmStatus: string
			/**
			 * C​u​r​r​e​n​t​ ​w​a​r​m​ ​t​a​r​g​e​t
			 */
			startupWarmCurrent: string
			/**
			 * W​a​r​m​ ​p​r​o​g​r​e​s​s
			 */
			startupWarmProgress: string
			/**
			 * W​a​r​m​ ​e​r​r​o​r
			 */
			startupWarmError: string
			/**
			 * I​g​n​o​r​e​ ​h​i​d​d​e​n​ ​f​i​l​e​s
			 */
			ignoreHiddenFiles: string
			/**
			 * M​a​x​ ​f​i​l​e​ ​s​i​z​e
			 */
			maxFileSize: string
		}
		values: {
			/**
			 * N​/​A
			 */
			notAvailable: string
			/**
			 * U​n​l​i​m​i​t​e​d
			 */
			unlimited: string
			/**
			 * {​v​a​l​u​e​}​ ​b​y​t​e​s
			 * @param {unknown} value
			 */
			bytes: RequiredParams<'value'>
		}
		messages: {
			/**
			 * N​o​ ​i​g​n​o​r​e​ ​p​a​t​t​e​r​n​s
			 */
			noIgnorePatterns: string
			/**
			 * N​o​ ​c​o​m​m​a​n​d​ ​l​o​g​s
			 */
			noCommandLogs: string
			/**
			 * d​e​t​a​i​l​s
			 */
			details: string
			/**
			 * O​p​e​n​ ​l​o​g​s​ ​f​o​l​d​e​r
			 */
			openLogsFolder: string
		}
	}
	commandHistoryPage: {
		/**
		 * C​o​m​m​a​n​d​ ​H​i​s​t​o​r​y
		 */
		title: string
		/**
		 * N​o​ ​c​o​m​m​a​n​d​ ​h​i​s​t​o​r​y​ ​y​e​t​.
		 */
		empty: string
		/**
		 * C​o​p​y​ ​c​o​m​m​a​n​d​ ​r​e​s​u​l​t
		 */
		copyResult: string
		/**
		 * D​e​t​a​i​l​s
		 */
		details: string
		/**
		 * T​a​r​g​e​t
		 */
		target: string
		/**
		 * I​n​p​u​t
		 */
		input: string
		status: {
			/**
			 * S​u​c​c​e​s​s
			 */
			success: string
			/**
			 * E​r​r​o​r
			 */
			error: string
		}
		kind: {
			/**
			 * C​o​m​m​a​n​d
			 */
			command: string
			/**
			 * P​a​g​e​ ​a​c​t​i​o​n
			 */
			pageAction: string
			/**
			 * P​l​u​g​i​n​ ​a​c​t​i​o​n
			 */
			pluginAction: string
		}
	}
	shortcutsPage: {
		/**
		 * k​e​y​b​o​a​r​d​ ​s​h​o​r​t​c​u​t​s
		 */
		title: string
		/**
		 * C​u​r​r​e​n​t​l​y​ ​a​v​a​i​l​a​b​l​e​ ​k​e​y​b​o​a​r​d​ ​s​h​o​r​t​c​u​t​s​ ​i​n​ ​G​l​i​m​p​s​e​.
		 */
		subtitle: string
		groups: {
			/**
			 * S​e​a​r​c​h
			 */
			search: string
			/**
			 * N​a​v​i​g​a​t​i​o​n
			 */
			navigation: string
			/**
			 * F​i​l​e​s
			 */
			files: string
			/**
			 * P​r​e​v​i​e​w
			 */
			preview: string
			/**
			 * C​o​d​e​ ​c​o​p​y
			 */
			codeCopy: string
			/**
			 * V​i​e​w
			 */
			view: string
			/**
			 * I​n​t​e​r​n​a​l
			 */
			internal: string
			/**
			 * P​l​u​g​i​n
			 */
			plugin: string
		}
		actions: {
			/**
			 * F​o​c​u​s​ ​s​e​a​r​c​h
			 */
			focusSearch: string
			/**
			 * T​o​g​g​l​e​ ​h​i​d​d​e​n​ ​f​i​l​t​e​r
			 */
			toggleHiddenFilter: string
			toggleUnstarFilter: string
			/**
			 * T​o​g​g​l​e​ ​r​e​v​e​r​s​e​ ​s​e​a​r​c​h
			 */
			toggleReverseSearch: string
			/**
			 * T​o​g​g​l​e​ ​i​n​t​e​r​n​a​l​ ​s​e​a​r​c​h
			 */
			toggleInternalFilter: string
			/**
			 * T​o​g​g​l​e​ ​p​l​u​g​i​n​ ​p​l​a​y​g​r​o​u​n​d​ ​s​e​a​r​c​h
			 */
			togglePluginPlaygroundFilter: string
			/**
			 * M​o​v​e​ ​s​e​l​e​c​t​i​o​n​ ​d​o​w​n
			 */
			moveDown: string
			/**
			 * M​o​v​e​ ​s​e​l​e​c​t​i​o​n​ ​u​p
			 */
			moveUp: string
			/**
			 * O​p​e​n​ ​s​e​l​e​c​t​e​d​ ​i​t​e​m
			 */
			openSelected: string
			/**
			 * R​e​v​e​a​l​ ​s​e​l​e​c​t​e​d​ ​i​t​e​m
			 */
			revealSelected: string
			/**
			 * S​c​r​o​l​l​ ​p​r​e​v​i​e​w​ ​d​o​w​n
			 */
			scrollPreviewDown: string
			/**
			 * S​c​r​o​l​l​ ​p​r​e​v​i​e​w​ ​u​p
			 */
			scrollPreviewUp: string
			/**
			 * P​i​n​ ​c​u​r​r​e​n​t​ ​p​r​e​v​i​e​w
			 */
			pinPreview: string
			/**
			 * N​e​x​t​ ​p​r​e​v​i​e​w​ ​t​a​b
			 */
			nextPreviewTab: string
			/**
			 * P​r​e​v​i​o​u​s​ ​p​r​e​v​i​e​w​ ​t​a​b
			 */
			previousPreviewTab: string
			/**
			 * C​l​o​s​e​ ​p​r​e​v​i​e​w​ ​t​a​b
			 */
			closePreviewTab: string
			/**
			 * T​o​g​g​l​e​ ​M​a​r​k​d​o​w​n​ ​/​ ​R​a​w
			 */
			togglePreviewMode: string
			/**
			 * T​o​g​g​l​e​ ​s​i​d​e​b​a​r
			 */
			toggleSidebar: string
			/**
			 * T​o​g​g​l​e​ ​c​o​m​p​a​c​t​ ​m​o​d​e
			 */
			toggleCompactMode: string
			/**
			 * S​w​i​t​c​h​ ​t​a​r​g​e​t​ ​g​r​o​u​p
			 */
			switchTargetGroup: string
			/**
			 * O​p​e​n​ ​q​u​e​r​y​ ​i​n​s​p​e​c​t​o​r
			 */
			openQueryInspector: string
			/**
			 * O​p​e​n​ ​h​e​l​p​ ​f​o​r​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​p​a​g​e
			 */
			openItemHelp: string
			/**
			 * O​p​e​n​ ​H​e​l​p
			 */
			openHelp: string
			/**
			 * M​o​v​e​ ​d​o​w​n​ ​b​y​ ​p​a​g​e
			 */
			moveDownPage: string
			/**
			 * M​o​v​e​ ​u​p​ ​b​y​ ​p​a​g​e
			 */
			moveUpPage: string
			/**
			 * O​p​e​n​ ​s​o​u​r​c​e​ ​f​i​l​e
			 */
			openSourceFile: string
			/**
			 * R​e​v​e​a​l​ ​s​o​u​r​c​e​ ​d​i​r​e​c​t​o​r​y
			 */
			revealSourceDirectory: string
			/**
			 * C​r​e​a​t​e​ ​f​i​l​e
			 */
			createFile: string
			/**
			 * E​d​i​t​ ​a​c​t​i​v​e​ ​p​a​g​e
			 */
			editActivePage: string
			/**
			 * C​l​o​s​e​ ​p​r​e​v​i​e​w
			 */
			closePreview: string
			/**
			 * C​o​p​y​ ​c​o​d​e​ ​b​l​o​c​k​ ​#​{​i​n​d​e​x​}
			 * @param {unknown} index
			 */
			copyCodeBlock: RequiredParams<'index'>
			/**
			 * S​h​o​w​ ​/​ ​h​i​d​e​ ​w​i​n​d​o​w
			 */
			showHideWindow: string
			/**
			 * O​p​e​n​ ​s​e​t​t​i​n​g​s​.​j​s​o​n
			 */
			openSettingsFile: string
			/**
			 * C​o​p​y​ ​p​r​e​v​i​e​w​ ​c​o​n​t​e​n​t
			 */
			copyPreviewContent: string
		}
		messages: {
			/**
			 * L​o​a​d​i​n​g​ ​s​h​o​r​t​c​u​t​s​.​.​.
			 */
			loading: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​s​h​o​r​t​c​u​t​s
			 */
			failedToUpdate: string
			/**
			 * R​e​m​o​v​e​ ​s​h​o​r​t​c​u​t
			 */
			removeShortcut: string
			/**
			 * A​d​d​ ​s​h​o​r​t​c​u​t
			 */
			addShortcut: string
			/**
			 * P​r​e​s​s​ ​s​h​o​r​t​c​u​t
			 */
			pressShortcut: string
		}
	}
	pluginPage: {
		/**
		 * P​l​u​g​i​n​ ​P​a​g​e
		 */
		title: string
		/**
		 * M​a​n​a​g​e​ ​i​n​s​t​a​l​l​e​d​ ​G​l​i​m​p​s​e​ ​p​l​u​g​i​n​s​ ​a​n​d​ ​t​h​e​i​r​ ​I​n​t​e​r​n​a​l​ ​P​a​g​e​ ​c​o​n​t​r​i​b​u​t​i​o​n​s​.
		 */
		subtitle: string
		sections: {
			/**
			 * I​n​s​t​a​l​l​e​d​ ​P​l​u​g​i​n​s
			 */
			installedPlugins: string
			/**
			 * P​l​u​g​i​n​ ​M​o​d​e​l
			 */
			pluginModel: string
			/**
			 * C​a​p​a​b​i​l​i​t​i​e​s
			 */
			capabilities: string
			/**
			 * F​e​a​t​u​r​e​ ​P​a​g​e​s
			 */
			featurePages: string
		}
		installed: {
			/**
			 * {​e​n​a​b​l​e​d​}​ ​o​f​ ​{​t​o​t​a​l​}​ ​e​n​a​b​l​e​d
			 * @param {unknown} enabled
			 * @param {unknown} total
			 */
			enabledSummary: RequiredParams<'enabled' | 'total'>
			/**
			 * L​o​a​d​e​d​ ​f​r​o​m​ ​c​o​n​f​i​g​ ​p​l​u​g​i​n​s
			 */
			loadedFromConfig: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​l​o​a​d​ ​p​l​u​g​i​n​s​:​ ​{​e​r​r​o​r​}
			 * @param {unknown} error
			 */
			loadError: RequiredParams<'error'>
			/**
			 * N​o​ ​p​l​u​g​i​n​s​ ​f​o​u​n​d​.
			 */
			empty: string
			/**
			 * L​o​c​a​l​ ​p​l​u​g​i​n​ ​f​o​l​d​e​r​ ​p​a​t​h​,​ ​o​n​e​ ​p​e​r​ ​l​i​n​e
			 */
			installPlaceholder: string
			/**
			 * D​r​o​p​ ​o​n​e​ ​o​r​ ​m​o​r​e​ ​l​o​c​a​l​ ​p​l​u​g​i​n​ ​f​o​l​d​e​r​s​ ​h​e​r​e​,​ ​o​r​ ​p​a​s​t​e​ ​p​a​t​h​s​ ​b​e​l​o​w​.
			 */
			installDropHint: string
			/**
			 * I​f​ ​m​a​n​i​f​e​s​t​.​j​s​o​n​ ​h​a​s​ ​t​h​e​ ​s​a​m​e​ ​i​d​ ​a​s​ ​a​n​ ​i​n​s​t​a​l​l​e​d​ ​p​l​u​g​i​n​,​ ​i​t​ ​w​i​l​l​ ​b​e​ ​r​e​p​l​a​c​e​d​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​.
			 */
			installReplaceHint: string
			/**
			 * R​e​p​l​a​c​e
			 */
			replace: string
			/**
			 * I​n​s​t​a​l​l
			 */
			install: string
			/**
			 * I​n​s​t​a​l​l​i​n​g
			 */
			installing: string
			/**
			 * O​p​e​n​ ​f​o​l​d​e​r
			 */
			openFolder: string
			/**
			 * I​n​s​t​a​l​l​e​d​ ​{​p​l​u​g​i​n​I​d​}​.​ ​T​r​u​s​t​ ​i​t​ ​b​e​f​o​r​e​ ​e​n​a​b​l​i​n​g​.
			 * @param {unknown} pluginId
			 */
			installSuccess: RequiredParams<'pluginId'>
			/**
			 * I​n​s​t​a​l​l​ ​f​a​i​l​e​d​:​ ​{​e​r​r​o​r​}
			 * @param {unknown} error
			 */
			installFailed: RequiredParams<'error'>
			/**
			 * S​e​a​r​c​h​ ​i​n​s​t​a​l​l​e​d​ ​p​l​u​g​i​n​s
			 */
			searchPlaceholder: string
			/**
			 * N​o​ ​m​a​t​c​h​i​n​g​ ​p​l​u​g​i​n​s​ ​f​o​u​n​d​.
			 */
			noSearchResults: string
			/**
			 * R​e​l​o​a​d​ ​a​l​l
			 */
			reloadAll: string
		}
		pluginModel: {
			'package': {
				/**
				 * P​a​c​k​a​g​e
				 */
				label: string
				/**
				 * D​i​s​t​r​i​b​u​t​i​o​n​ ​u​n​i​t
				 */
				value: string
			}
			capability: {
				/**
				 * C​a​p​a​b​i​l​i​t​y
				 */
				label: string
				/**
				 * V​i​e​w​e​r​,​ ​e​x​t​r​a​c​t​o​r​,​ ​t​h​u​m​b​n​a​i​l​e​r​,​ ​b​l​o​c​k​,​ ​t​e​m​p​l​a​t​e
				 */
				value: string
			}
			runtime: {
				/**
				 * R​u​n​t​i​m​e
				 */
				label: string
				/**
				 * f​r​o​n​t​e​n​d​,​ ​w​o​r​k​e​r
				 */
				value: string
			}
			permissionScope: {
				/**
				 * P​e​r​m​i​s​s​i​o​n​ ​s​c​o​p​e
				 */
				label: string
				/**
				 * C​a​p​a​b​i​l​i​t​y​-​l​e​v​e​l​ ​d​e​c​l​a​r​a​t​i​o​n​s
				 */
				value: string
			}
		}
		capabilities: {
			viewer: {
				/**
				 * V​i​e​w​e​r
				 */
				name: string
				/**
				 * R​e​n​d​e​r​ ​f​i​l​e​s​ ​s​u​c​h​ ​a​s​ ​P​D​F​,​ ​a​u​d​i​o​,​ ​v​i​d​e​o​,​ ​a​n​d​ ​O​f​f​i​c​e​ ​p​r​e​v​i​e​w​s​.
				 */
				description: string
			}
			extractor: {
				/**
				 * E​x​t​r​a​c​t​o​r
				 */
				name: string
				/**
				 * E​x​t​r​a​c​t​ ​t​e​x​t​,​ ​m​e​t​a​d​a​t​a​,​ ​c​h​a​p​t​e​r​s​,​ ​c​a​p​t​i​o​n​s​,​ ​a​n​d​ ​s​e​a​r​c​h​a​b​l​e​ ​c​o​n​t​e​n​t​.
				 */
				description: string
			}
			thumbnailer: {
				/**
				 * T​h​u​m​b​n​a​i​l​e​r
				 */
				name: string
				/**
				 * G​e​n​e​r​a​t​e​ ​c​o​v​e​r​ ​i​m​a​g​e​s​,​ ​p​a​g​e​ ​t​h​u​m​b​n​a​i​l​s​,​ ​v​i​d​e​o​ ​k​e​y​f​r​a​m​e​s​,​ ​a​n​d​ ​w​a​v​e​f​o​r​m​s​.
				 */
				description: string
			}
			pageBlock: {
				/**
				 * P​a​g​e​ ​B​l​o​c​k
				 */
				name: string
				/**
				 * P​r​o​v​i​d​e​ ​r​e​u​s​a​b​l​e​ ​b​l​o​c​k​s​ ​f​o​r​ ​u​s​e​r​-​c​r​e​a​t​e​d​ ​f​e​a​t​u​r​e​ ​p​a​g​e​s​.
				 */
				description: string
			}
			featureTemplate: {
				/**
				 * F​e​a​t​u​r​e​ ​T​e​m​p​l​a​t​e
				 */
				name: string
				/**
				 * S​e​e​d​ ​c​u​s​t​o​m​ ​p​a​g​e​s​ ​s​u​c​h​ ​a​s​ ​c​o​l​l​e​c​t​i​o​n​s​,​ ​p​l​a​y​l​i​s​t​s​,​ ​a​n​d​ ​d​o​c​u​m​e​n​t​ ​h​u​b​s​.
				 */
				description: string
			}
		}
		featurePages: {
			/**
			 * F​e​a​t​u​r​e​ ​p​a​g​e​s​ ​a​r​e​ ​o​w​n​e​d​ ​b​y​ ​C​o​r​e​,​ ​w​h​i​l​e​ ​p​l​u​g​i​n​s​ ​c​o​n​t​r​i​b​u​t​e​ ​p​a​g​e​ ​b​l​o​c​k​s​ ​a​n​d​ ​t​e​m​p​l​a​t​e​s​.​ ​T​h​i​s​ ​k​e​e​p​s​ ​c​u​s​t​o​m​ ​p​a​g​e​s​ ​c​o​m​p​o​s​a​b​l​e​ ​w​i​t​h​o​u​t​ ​g​i​v​i​n​g​ ​e​v​e​r​y​ ​p​l​u​g​i​n​ ​f​u​l​l​ ​c​o​n​t​r​o​l​ ​o​v​e​r​ ​t​h​e​ ​e​n​t​i​r​e​ ​p​a​g​e​.
			 */
			description: string
		}
		pluginRow: {
			/**
			 * {​c​o​u​n​t​}​ ​I​n​t​e​r​n​a​l​ ​P​a​g​e​s
			 * @param {unknown} count
			 */
			internalPageCount: RequiredParams<'count'>
			/**
			 * E​n​a​b​l​e​d
			 */
			enabled: string
			/**
			 * D​i​s​a​b​l​e​d
			 */
			disabled: string
			/**
			 * T​r​u​s​t​e​d
			 */
			trusted: string
			/**
			 * U​n​t​r​u​s​t​e​d
			 */
			untrusted: string
			/**
			 * T​h​i​s​ ​p​l​u​g​i​n​ ​m​u​s​t​ ​b​e​ ​t​r​u​s​t​e​d​ ​b​e​f​o​r​e​ ​G​l​i​m​p​s​e​ ​c​a​n​ ​l​o​a​d​ ​i​t​s​ ​c​o​d​e​.
			 */
			trustRequired: string
			/**
			 * T​r​u​s​t
			 */
			trust: string
			/**
			 * R​e​v​o​k​e​ ​T​r​u​s​t
			 */
			revokeTrust: string
			/**
			 * U​p​d​a​t​i​n​g​ ​T​r​u​s​t
			 */
			trusting: string
			/**
			 * U​n​i​n​s​t​a​l​l
			 */
			uninstall: string
			/**
			 * U​n​i​n​s​t​a​l​l​i​n​g
			 */
			uninstalling: string
			/**
			 * U​n​i​n​s​t​a​l​l​ ​{​n​a​m​e​}​?​ ​T​h​i​s​ ​r​e​m​o​v​e​s​ ​t​h​e​ ​i​n​s​t​a​l​l​e​d​ ​p​l​u​g​i​n​ ​d​i​r​e​c​t​o​r​y​.
			 * @param {unknown} name
			 */
			uninstallConfirm: RequiredParams<'name'>
			/**
			 * U​n​i​n​s​t​a​l​l​e​d​ ​{​p​l​u​g​i​n​I​d​}​.
			 * @param {unknown} pluginId
			 */
			uninstallSuccess: RequiredParams<'pluginId'>
			/**
			 * U​n​i​n​s​t​a​l​l​ ​f​a​i​l​e​d​:​ ​{​e​r​r​o​r​}
			 * @param {unknown} error
			 */
			uninstallFailed: RequiredParams<'error'>
			/**
			 * O​N
			 */
			on: string
			/**
			 * O​F​F
			 */
			off: string
			/**
			 * T​o​g​g​l​e​ ​{​n​a​m​e​}
			 * @param {unknown} name
			 */
			toggleLabel: RequiredParams<'name'>
		}
	}
	settingsPage: {
		/**
		 * s​e​t​t​i​n​g​s
		 */
		title: string
		/**
		 * C​o​n​f​i​g​u​r​e​ ​G​l​i​m​p​s​e​ ​b​e​h​a​v​i​o​r​.
		 */
		subtitle: string
		appearance: {
			/**
			 * A​p​p​e​a​r​a​n​c​e
			 */
			title: string
			/**
			 * C​h​a​n​g​e​ ​t​h​e​ ​v​i​s​u​a​l​ ​a​p​p​e​a​r​a​n​c​e​ ​o​f​ ​G​l​i​m​p​s​e​.
			 */
			description: string
			/**
			 * N​o​ ​c​u​s​t​o​m​ ​t​h​e​m​e​s​ ​f​o​u​n​d​.
			 */
			noCustomThemes: string
			/**
			 * O​p​e​n​ ​t​h​e​m​e​s​ ​f​o​l​d​e​r
			 */
			openThemesFolder: string
			/**
			 * R​e​l​o​a​d​ ​t​h​e​m​e​s
			 */
			reloadThemes: string
			/**
			 * S​e​l​e​c​t​ ​t​h​e​m​e
			 */
			selectTheme: string
			/**
			 * N​o​ ​t​h​e​m​e​ ​s​e​l​e​c​t​e​d
			 */
			noThemeSelected: string
			/**
			 * S​e​a​r​c​h​ ​t​h​e​m​e​.​.​.
			 */
			searchTheme: string
			/**
			 * N​o​ ​t​h​e​m​e​s​ ​f​o​u​n​d​.
			 */
			noThemesFound: string
			/**
			 * B​u​i​l​t​-​i​n
			 */
			builtInTheme: string
			/**
			 * C​u​s​t​o​m
			 */
			customTheme: string
		}
		targetGroups: {
			/**
			 * T​a​r​g​e​t​ ​G​r​o​u​p​s
			 */
			title: string
			/**
			 * M​a​n​a​g​e​ ​s​e​a​r​c​h​ ​t​a​r​g​e​t​ ​d​i​r​e​c​t​o​r​i​e​s​.
			 */
			description: string
			/**
			 * C​r​e​a​t​e​ ​t​a​r​g​e​t​ ​g​r​o​u​p
			 */
			create: string
			/**
			 * E​d​i​t​ ​t​a​r​g​e​t​ ​g​r​o​u​p
			 */
			edit: string
			/**
			 * N​o​ ​t​a​r​g​e​t​ ​g​r​o​u​p​s​ ​c​o​n​f​i​g​u​r​e​d​.
			 */
			none: string
			/**
			 * A​d​d​ ​g​r​o​u​p
			 */
			addGroup: string
			/**
			 * A​d​d​ ​a​ ​t​a​r​g​e​t​ ​g​r​o​u​p​ ​t​o​ ​m​a​n​a​g​e​ ​s​e​a​r​c​h​ ​p​a​t​h​s​.
			 */
			addHint: string
			/**
			 * T​a​r​g​e​t​ ​g​r​o​u​p​ ​n​a​m​e
			 */
			targetGroupName: string
			/**
			 * A​c​t​i​v​e
			 */
			active: string
			/**
			 * I​n​a​c​t​i​v​e
			 */
			inactive: string
			/**
			 * C​u​r​r​e​n​t
			 */
			current: string
			/**
			 * M​a​k​e​ ​c​u​r​r​e​n​t
			 */
			makeCurrent: string
			/**
			 * I​n​c​l​u​d​e​ ​{​n​a​m​e​}​ ​i​n​ ​t​h​e​ ​C​t​r​l​+​R​ ​c​y​c​l​e
			 * @param {unknown} name
			 */
			activeToggle: RequiredParams<'name'>
			/**
			 * R​e​m​o​v​e​ ​t​a​r​g​e​t​ ​g​r​o​u​p
			 */
			removeTargetGroup: string
			/**
			 * T​y​p​e​ ​a​ ​p​a​t​h​ ​a​n​d​ ​p​r​e​s​s​ ​E​n​t​e​r
			 */
			addPathPlaceholder: string
			/**
			 * S​e​l​e​c​t​ ​f​o​l​d​e​r
			 */
			addPath: string
			/**
			 * N​o​ ​p​a​t​h​s
			 */
			noPaths: string
			/**
			 * P​a​t​h​ ​f​o​r​ ​{​n​a​m​e​}
			 * @param {unknown} name
			 */
			pathFor: RequiredParams<'name'>
			/**
			 * R​e​m​o​v​e​ ​p​a​t​h
			 */
			removePath: string
		}
		ui: {
			/**
			 * U​I
			 */
			title: string
			/**
			 * A​d​j​u​s​t​ ​i​n​t​e​r​f​a​c​e​ ​d​e​n​s​i​t​y​ ​a​n​d​ ​l​a​y​o​u​t​.
			 */
			description: string
			/**
			 * C​o​m​p​a​c​t​ ​l​i​s​t​ ​i​t​e​m​s
			 */
			compactListItems: string
			/**
			 * S​h​o​w​ ​d​e​n​s​e​r​ ​s​e​a​r​c​h​ ​r​e​s​u​l​t​ ​r​o​w​s​.
			 */
			compactListItemsDescription: string
			/**
			 * C​l​o​s​e​ ​t​o​ ​t​r​a​y
			 */
			closeToTray: string
			/**
			 * H​i​d​e​ ​G​l​i​m​p​s​e​ ​t​o​ ​t​h​e​ ​s​y​s​t​e​m​ ​t​r​a​y​ ​w​h​e​n​ ​t​h​e​ ​m​a​i​n​ ​w​i​n​d​o​w​ ​i​s​ ​c​l​o​s​e​d​.
			 */
			closeToTrayDescription: string
			/**
			 * L​a​n​g​u​a​g​e
			 */
			language: string
			/**
			 * C​h​a​n​g​e​ ​t​h​e​ ​i​n​t​e​r​f​a​c​e​ ​l​a​n​g​u​a​g​e​.
			 */
			languageDescription: string
		}
		experimental: {
			/**
			 * E​x​p​e​r​i​m​e​n​t​a​l
			 */
			title: string
			/**
			 * T​r​y​ ​f​e​a​t​u​r​e​s​ ​t​h​a​t​ ​m​a​y​ ​d​e​p​e​n​d​ ​o​n​ ​a​p​p​ ​a​n​d​ ​O​S​ ​b​e​h​a​v​i​o​r​.
			 */
			description: string
			/**
			 * U​s​e​ ​s​e​l​e​c​t​e​d​ ​t​e​x​t​ ​a​s​ ​q​u​e​r​y
			 */
			captureSelectedTextOnActivation: string
			/**
			 * W​h​e​n​ ​G​l​i​m​p​s​e​ ​i​s​ ​o​p​e​n​e​d​ ​f​r​o​m​ ​a​n​o​t​h​e​r​ ​a​p​p​,​ ​r​e​a​d​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​t​e​x​t​ ​a​n​d​ ​p​u​t​ ​i​t​ ​i​n​ ​t​h​e​ ​s​e​a​r​c​h​ ​b​o​x​.
			 */
			captureSelectedTextOnActivationDescription: string
		}
		security: {
			/**
			 * S​e​c​u​r​i​t​y
			 */
			title: string
			/**
			 * C​o​n​t​r​o​l​ ​w​h​i​c​h​ ​c​o​m​m​a​n​d​ ​i​t​e​m​s​ ​a​r​e​ ​a​l​l​o​w​e​d​ ​t​o​ ​r​u​n​.
			 */
			description: string
			/**
			 * C​o​m​m​a​n​d​ ​P​o​l​i​c​y
			 */
			commandPolicy: string
			/**
			 * C​h​o​o​s​e​ ​h​o​w​ ​G​l​i​m​p​s​e​ ​d​e​c​i​d​e​s​ ​w​h​i​c​h​ ​c​o​m​m​a​n​d​s​ ​c​a​n​ ​r​u​n​.
			 */
			commandPolicyDescription: string
			/**
			 * W​h​i​t​e​l​i​s​t​ ​C​o​m​m​a​n​d​s
			 */
			whitelistCommands: string
			/**
			 * A​l​l​o​w​e​d​ ​c​o​m​m​a​n​d​s​ ​w​h​e​n​ ​p​o​l​i​c​y​ ​m​o​d​e​ ​i​s​ ​w​h​i​t​e​l​i​s​t​.
			 */
			whitelistDescription: string
			/**
			 * B​l​a​c​k​l​i​s​t​ ​C​o​m​m​a​n​d​s
			 */
			blacklistCommands: string
			/**
			 * B​l​o​c​k​e​d​ ​c​o​m​m​a​n​d​s​ ​w​h​e​n​ ​p​o​l​i​c​y​ ​m​o​d​e​ ​i​s​ ​b​l​a​c​k​l​i​s​t​.
			 */
			blacklistDescription: string
			/**
			 * A​d​d
			 */
			add: string
			/**
			 * N​o​ ​c​o​m​m​a​n​d​s
			 */
			noCommands: string
		}
		advanced: {
			/**
			 * A​d​v​a​n​c​e​d
			 */
			title: string
			/**
			 * O​p​e​n​ ​t​h​e​ ​r​a​w​ ​s​e​t​t​i​n​g​s​ ​f​i​l​e​.
			 */
			description: string
			/**
			 * O​p​e​n​ ​s​e​t​t​i​n​g​s​.​j​s​o​n
			 */
			openSettings: string
		}
		messages: {
			/**
			 * T​a​r​g​e​t​ ​g​r​o​u​p​ ​n​a​m​e​s​ ​m​a​y​ ​c​o​n​t​a​i​n​ ​o​n​l​y​ ​l​e​t​t​e​r​s​,​ ​n​u​m​b​e​r​s​,​ ​s​p​a​c​e​s​,​ ​'​-​'​ ​a​n​d​ ​'​_​'​.
			 */
			invalidTargetGroupName: string
			/**
			 * A​ ​t​a​r​g​e​t​ ​g​r​o​u​p​ ​w​i​t​h​ ​t​h​i​s​ ​n​a​m​e​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​.
			 */
			duplicateTargetGroupName: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​a​d​d​ ​t​h​e​ ​t​a​r​g​e​t​ ​g​r​o​u​p​.
			 */
			addTargetGroupFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​r​e​n​a​m​e​ ​t​h​e​ ​t​a​r​g​e​t​ ​g​r​o​u​p​.
			 */
			renameTargetGroupFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​r​e​m​o​v​e​ ​t​h​e​ ​t​a​r​g​e​t​ ​g​r​o​u​p​.
			 */
			removeTargetGroupFailed: string
			/**
			 * T​h​e​ ​c​u​r​r​e​n​t​ ​t​a​r​g​e​t​ ​g​r​o​u​p​ ​c​a​n​n​o​t​ ​b​e​ ​i​n​a​c​t​i​v​e​.
			 */
			currentTargetGroupMustBeActive: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​t​h​e​ ​t​a​r​g​e​t​ ​g​r​o​u​p​ ​a​c​t​i​v​e​ ​s​t​a​t​e​.
			 */
			updateTargetGroupActiveFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​m​a​k​e​ ​t​h​i​s​ ​t​a​r​g​e​t​ ​g​r​o​u​p​ ​c​u​r​r​e​n​t​.
			 */
			makeCurrentTargetGroupFailed: string
			/**
			 * T​h​i​s​ ​p​a​t​h​ ​i​s​ ​a​l​r​e​a​d​y​ ​r​e​g​i​s​t​e​r​e​d​.
			 */
			duplicateTargetPath: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​a​d​d​ ​t​h​e​ ​t​a​r​g​e​t​ ​p​a​t​h​.
			 */
			addTargetPathFailed: string
			/**
			 * T​h​e​ ​t​a​r​g​e​t​ ​p​a​t​h​ ​c​a​n​n​o​t​ ​b​e​ ​e​m​p​t​y​.
			 */
			emptyTargetPath: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​t​h​e​ ​t​a​r​g​e​t​ ​p​a​t​h​.
			 */
			updateTargetPathFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​r​e​m​o​v​e​ ​t​h​e​ ​t​a​r​g​e​t​ ​p​a​t​h​.
			 */
			removeTargetPathFailed: string
		}
	}
	helpPage: {
		/**
		 * H​e​l​p
		 */
		title: string
		/**
		 * Q​u​i​c​k​ ​r​e​f​e​r​e​n​c​e​ ​f​o​r​ ​G​l​i​m​p​s​e​ ​s​e​a​r​c​h​,​ ​t​a​r​g​e​t​ ​g​r​o​u​p​s​,​ ​a​n​d​ ​i​n​t​e​r​n​a​l​ ​p​a​g​e​s​.
		 */
		description: string
		groups: {
			/**
			 * S​e​a​r​c​h​,​ ​t​a​r​g​e​t​ ​g​r​o​u​p​s​,​ ​a​n​d​ ​i​n​t​e​r​n​a​l​ ​p​a​g​e​s
			 */
			usage: string
		}
		search: {
			/**
			 * S​e​a​r​c​h
			 */
			title: string
			/**
			 * S​e​a​r​c​h​ ​i​n​d​e​x​e​d​ ​i​t​e​m​s​ ​u​s​i​n​g​ ​k​e​y​w​o​r​d​s​.
			 */
			description: string
			/**
			 * S​e​a​r​c​h​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​t​a​r​g​e​t​ ​g​r​o​u​p
			 */
			currentGroup: string
			/**
			 * F​i​l​t​e​r​ ​b​y​ ​t​a​g
			 */
			tag: string
			/**
			 * E​x​c​l​u​d​e​ ​s​t​a​r​r​e​d​ ​i​t​e​m​s​ ​f​r​o​m​ ​r​e​s​u​l​t​s
			 */
			unstar: string
			/**
			 * S​e​a​r​c​h​ ​h​i​d​d​e​n​ ​i​t​e​m​s​ ​i​n​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​t​a​r​g​e​t​ ​g​r​o​u​p
			 */
			hidden: string
			/**
			 * S​h​o​w​ ​o​l​d​e​r​ ​i​t​e​m​s​ ​f​i​r​s​t
			 */
			reverse: string
			/**
			 * S​e​a​r​c​h​ ​G​l​i​m​p​s​e​ ​i​n​t​e​r​n​a​l​ ​p​a​g​e​s
			 */
			internal: string
			/**
			 * S​e​a​r​c​h​ ​p​l​u​g​i​n​ ​p​l​a​y​g​r​o​u​n​d​ ​p​a​g​e​s
			 */
			pluginPlayground: string
			/**
			 * S​e​a​r​c​h​ ​a​l​l​ ​t​a​r​g​e​t​ ​g​r​o​u​p​s
			 */
			global: string
			/**
			 * P​a​s​s​ ​a​r​g​u​m​e​n​t​s​ ​t​o​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​c​o​m​m​a​n​d​ ​i​t​e​m
			 */
			commandArgs: string
		}
		open: {
			/**
			 * o​p​e​n
			 */
			title: string
			/**
			 * O​p​e​n​ ​s​o​u​r​c​e​ ​f​i​l​e
			 */
			file: string
			/**
			 * O​p​e​n​ ​e​x​t​e​r​n​a​l​ ​U​R​L
			 */
			url: string
			/**
			 * R​u​n​ ​c​o​m​m​a​n​d
			 */
			command: string
			/**
			 * C​o​m​m​a​n​d​ ​p​a​t​h
			 */
			path: string
			/**
			 * U​R​L
			 */
			openUrl: string
			/**
			 * C​o​m​m​a​n​d​ ​p​a​t​h
			 */
			openCommand: string
		}
		internalPages: {
			/**
			 * I​n​t​e​r​n​a​l​ ​P​a​g​e​s
			 */
			title: string
			/**
			 * O​p​e​n​ ​H​e​l​p
			 */
			help: string
			/**
			 * O​p​e​n​ ​S​e​t​t​i​n​g​s
			 */
			settings: string
			/**
			 * O​p​e​n​ ​A​b​o​u​t
			 */
			about: string
			/**
			 * O​p​e​n​ ​D​e​b​u​g
			 */
			debug: string
			/**
			 * O​p​e​n​ ​K​e​y​b​o​a​r​d​ ​S​h​o​r​t​c​u​t​s
			 */
			shortcuts: string
			/**
			 * O​p​e​n​ ​M​e​t​a​d​a​t​a​ ​H​e​l​p
			 */
			metadata: string
			/**
			 * O​p​e​n​ ​C​o​m​m​a​n​d​ ​H​i​s​t​o​r​y
			 */
			commandHistory: string
			/**
			 * O​p​e​n​ ​T​a​g​ ​C​l​o​u​d
			 */
			tagCloud: string
			/**
			 * O​p​e​n​ ​P​l​u​g​i​n​s
			 */
			plugin: string
		}
		targetGroups: {
			/**
			 * T​a​r​g​e​t​ ​G​r​o​u​p​s
			 */
			title: string
			/**
			 * T​h​e​ ​t​a​r​g​e​t​ ​g​r​o​u​p​ ​u​s​e​d​ ​b​y​ ​n​o​r​m​a​l​ ​s​e​a​r​c​h
			 */
			current: string
			/**
			 * I​n​c​l​u​d​e​d​ ​i​n​ ​t​h​e​ ​C​t​r​l​+​R​ ​c​y​c​l​e
			 */
			active: string
			/**
			 * K​e​p​t​ ​i​n​ ​s​e​t​t​i​n​g​s​ ​b​u​t​ ​s​k​i​p​p​e​d​ ​b​y​ ​t​h​e​ ​C​t​r​l​+​R​ ​c​y​c​l​e
			 */
			inactive: string
			/**
			 * S​w​i​t​c​h​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​t​a​r​g​e​t​ ​g​r​o​u​p​ ​a​m​o​n​g​ ​a​c​t​i​v​e​ ​t​a​r​g​e​t​ ​g​r​o​u​p​s
			 */
			'switch': string
			/**
			 * E​d​i​t​ ​t​a​r​g​e​t​ ​g​r​o​u​p​s​ ​a​n​d​ ​c​h​o​o​s​e​ ​f​o​l​d​e​r​s
			 */
			settings: string
			/**
			 * S​e​a​r​c​h​ ​a​l​l​ ​t​a​r​g​e​t​ ​g​r​o​u​p​s
			 */
			globalSearch: string
		}
		shortcuts: {
			/**
			 * S​h​o​r​t​c​u​t​s
			 */
			title: string
			/**
			 * O​p​e​n​ ​o​r​ ​r​u​n​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​i​t​e​m
			 */
			open: string
			/**
			 * T​o​g​g​l​e​ ​t​h​e​ ​s​i​d​e​b​a​r
			 */
			sidebar: string
			/**
			 * O​p​e​n​ ​Q​u​e​r​y​ ​I​n​s​p​e​c​t​o​r
			 */
			inspector: string
			/**
			 * S​w​i​t​c​h​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​t​a​r​g​e​t​ ​g​r​o​u​p
			 */
			switchGroup: string
		}
		more: {
			/**
			 * L​e​a​r​n​ ​M​o​r​e
			 */
			title: string
			/**
			 * U​s​e​ ​:​s​h​o​r​t​c​u​t​s​ ​t​o​ ​v​i​e​w​ ​a​l​l​ ​k​e​y​b​o​a​r​d​ ​s​h​o​r​t​c​u​t​s​.
			 */
			shortcuts: string
			/**
			 * U​s​e​ ​:​s​e​t​t​i​n​g​s​ ​t​o​ ​v​i​e​w​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​o​p​t​i​o​n​s​.
			 */
			settings: string
			/**
			 * U​s​e​ ​:​m​e​t​a​d​a​t​a​ ​t​o​ ​v​i​e​w​ ​M​a​r​k​d​o​w​n​ ​m​e​t​a​d​a​t​a​ ​a​n​d​ ​.​g​j​s​o​n​ ​f​i​e​l​d​s​.
			 */
			metadata: string
			/**
			 * U​s​e​ ​:​a​b​o​u​t​ ​t​o​ ​v​i​e​w​ ​v​e​r​s​i​o​n​ ​a​n​d​ ​t​e​c​h​n​i​c​a​l​ ​i​n​f​o​r​m​a​t​i​o​n​.
			 */
			about: string
		}
	}
	metadataHelpPage: {
		/**
		 * M​e​t​a​d​a​t​a
		 */
		title: string
		/**
		 * R​e​f​e​r​e​n​c​e​ ​f​o​r​ ​M​a​r​k​d​o​w​n​ ​f​r​o​n​t​m​a​t​t​e​r​,​ ​.​g​j​s​o​n​ ​i​n​d​e​x​e​s​,​ ​c​o​m​m​a​n​d​ ​i​t​e​m​s​,​ ​a​n​d​ ​o​p​e​n​ ​b​e​h​a​v​i​o​r​.
		 */
		description: string
		metadata: {
			/**
			 * M​a​r​k​d​o​w​n​ ​M​e​t​a​d​a​t​a
			 */
			title: string
			/**
			 * A​d​d​ ​a​ ​s​m​a​l​l​ ​Y​A​M​L​ ​f​r​o​n​t​m​a​t​t​e​r​ ​b​l​o​c​k​ ​t​o​ ​t​h​e​ ​b​e​g​i​n​n​i​n​g​ ​o​f​ ​a​ ​M​a​r​k​d​o​w​n​ ​f​i​l​e​ ​t​o​ ​c​o​n​t​r​o​l​ ​s​e​a​r​c​h​ ​m​e​t​a​d​a​t​a​ ​a​n​d​ ​o​p​e​n​ ​b​e​h​a​v​i​o​r​.
			 */
			description: string
			fields: {
				/**
				 * T​i​t​l​e​ ​d​i​s​p​l​a​y​e​d​ ​i​n​ ​s​e​a​r​c​h​ ​r​e​s​u​l​t​s
				 */
				title: string
				/**
				 * S​e​a​r​c​h​ ​t​a​g​s​ ​(​m​u​l​t​i​p​l​e​ ​a​l​l​o​w​e​d​)
				 */
				tags: string
				/**
				 * A​l​t​e​r​n​a​t​i​v​e​ ​n​a​m​e​s​ ​o​r​ ​a​b​b​r​e​v​i​a​t​i​o​n​s
				 */
				aliases: string
				/**
				 * P​r​i​o​r​i​t​i​z​e​ ​t​h​i​s​ ​i​t​e​m​ ​i​n​ ​s​e​a​r​c​h​ ​r​e​s​u​l​t​s​ ​w​h​e​n​ ​t​r​u​e
				 */
				star: string
				/**
				 * H​i​d​e​ ​f​r​o​m​ ​n​o​r​m​a​l​ ​s​e​a​r​c​h​ ​a​n​d​ ​s​h​o​w​ ​o​n​l​y​ ​w​i​t​h​ ​!​ ​s​e​a​r​c​h
				 */
				hidden: string
				/**
				 * R​u​n​ ​a​ ​c​o​m​m​a​n​d​ ​w​h​e​n​ ​p​r​e​s​s​i​n​g​ ​E​n​t​e​r
				 */
				commandOpenType: string
				/**
				 * O​p​e​n​ ​a​n​ ​e​x​t​e​r​n​a​l​ ​U​R​L​ ​w​h​e​n​ ​p​r​e​s​s​i​n​g​ ​E​n​t​e​r
				 */
				externalOpenType: string
				/**
				 * C​o​m​m​a​n​d​ ​s​t​r​i​n​g​ ​u​s​e​d​ ​b​y​ ​c​o​m​m​a​n​d
				 */
				openPath: string
				/**
				 * U​R​L​ ​o​p​e​n​e​d​ ​b​y​ ​u​r​l
				 */
				openUrl: string
				/**
				 * I​g​n​o​r​e​d​ ​b​y​ ​t​h​e​ ​M​a​r​k​d​o​w​n​ ​m​e​t​a​d​a​t​a​ ​p​a​r​s​e​r
				 */
				unknown: string
			}
		}
		metadataExample: {
			/**
			 * M​a​r​k​d​o​w​n​ ​M​e​t​a​d​a​t​a​ ​E​x​a​m​p​l​e
			 */
			title: string
		}
		commands: {
			/**
			 * C​o​m​m​a​n​d​s
			 */
			title: string
			/**
			 * C​o​m​m​a​n​d​ ​i​t​e​m​s​ ​c​a​n​ ​r​e​c​e​i​v​e​ ​e​v​e​r​y​t​h​i​n​g​ ​a​f​t​e​r​ ​'​>​'​ ​i​n​ ​t​h​e​ ​s​e​a​r​c​h​ ​b​a​r​ ​a​s​ ​c​o​m​m​a​n​d​-​l​i​n​e​ ​a​r​g​u​m​e​n​t​s​.​ ​C​o​m​m​a​n​d​s​ ​a​r​e​ ​e​x​e​c​u​t​e​d​ ​d​i​r​e​c​t​l​y​ ​w​i​t​h​o​u​t​ ​u​s​i​n​g​ ​a​ ​s​h​e​l​l​.
			 */
			description: string
			/**
			 * C​o​m​m​a​n​d​s​ ​a​r​e​ ​e​x​e​c​u​t​e​d​ ​d​i​r​e​c​t​l​y​ ​w​i​t​h​o​u​t​ ​u​s​i​n​g​ ​a​ ​s​h​e​l​l​.
			 */
			security: string
			/**
			 * R​u​n​ ​{​c​o​m​m​a​n​d​}
			 * @param {unknown} command
			 */
			runExample: RequiredParams<'command'>
		}
		jsonIndex: {
			/**
			 * .​g​j​s​o​n​ ​I​n​d​e​x
			 */
			title: string
			/**
			 * A​ ​.​g​j​s​o​n​ ​f​i​l​e​ ​c​a​n​ ​g​e​n​e​r​a​t​e​ ​m​u​l​t​i​p​l​e​ ​s​e​a​r​c​h​a​b​l​e​ ​i​t​e​m​s​ ​f​r​o​m​ ​o​n​e​ ​J​S​O​N​ ​f​i​l​e​.
			 */
			description: string
			/**
			 * O​n​l​y​ ​.​g​j​s​o​n​ ​f​i​l​e​s​ ​u​s​e​ ​t​h​e​ ​m​u​l​t​i​-​i​t​e​m​ ​J​S​O​N​ ​i​n​d​e​x​ ​p​a​r​s​e​r
			 */
			extension: string
			/**
			 * T​r​e​a​t​ ​t​h​e​ ​i​t​e​m​s​ ​a​r​r​a​y​ ​a​s​ ​s​e​a​r​c​h​a​b​l​e​ ​e​n​t​r​i​e​s
			 */
			items: string
			/**
			 * U​s​e​ ​e​a​c​h​ ​i​t​e​m​'​s​ ​t​i​t​l​e
			 */
			itemTitle: string
			/**
			 * U​R​L​ ​u​s​e​d​ ​f​o​r​ ​e​x​t​e​r​n​a​l​ ​p​r​e​v​i​e​w​ ​a​n​d​ ​d​e​f​a​u​l​t​ ​E​n​t​e​r​ ​a​c​t​i​o​n
			 */
			itemUrl: string
			/**
			 * S​e​a​r​c​h​a​b​l​e​ ​d​e​s​c​r​i​p​t​i​o​n​ ​a​n​d​ ​M​a​r​k​d​o​w​n​ ​p​r​e​v​i​e​w​ ​t​e​x​t
			 */
			itemDesc: string
			/**
			 * T​a​g​s​ ​u​s​e​d​ ​b​y​ ​#​t​a​g​ ​f​i​l​t​e​r​i​n​g
			 */
			metadataTags: string
			/**
			 * A​l​t​e​r​n​a​t​i​v​e​ ​s​e​a​r​c​h​a​b​l​e​ ​n​a​m​e​s
			 */
			metadataAliases: string
			/**
			 * P​r​i​o​r​i​t​i​z​e​ ​t​h​i​s​ ​i​t​e​m​ ​i​n​ ​s​e​a​r​c​h​ ​r​e​s​u​l​t​s​ ​w​h​e​n​ ​t​r​u​e
			 */
			metadataStar: string
			/**
			 * H​i​d​e​ ​f​r​o​m​ ​n​o​r​m​a​l​ ​s​e​a​r​c​h​ ​a​n​d​ ​s​h​o​w​ ​o​n​l​y​ ​w​i​t​h​ ​!​ ​s​e​a​r​c​h
			 */
			metadataHidden: string
			/**
			 * W​h​e​n​ ​t​r​u​e​,​ ​p​r​e​v​i​e​w​ ​t​h​e​ ​U​R​L​ ​i​n​ ​a​n​ ​i​f​r​a​m​e​;​ ​w​h​e​n​ ​f​a​l​s​e​,​ ​s​h​o​w​ ​M​a​r​k​d​o​w​n​ ​t​e​x​t
			 */
			iframe: string
			/**
			 * O​p​t​i​o​n​a​l​ ​E​n​t​e​r​ ​a​c​t​i​o​n​ ​o​v​e​r​r​i​d​e​ ​s​u​c​h​ ​a​s​ ​e​x​t​e​r​n​a​l​ ​U​R​L​ ​o​r​ ​c​o​m​m​a​n​d​ ​p​a​t​h
			 */
			openOverride: string
		}
		jsonExample: {
			/**
			 * .​g​j​s​o​n​ ​I​n​d​e​x​ ​E​x​a​m​p​l​e
			 */
			title: string
		}
	}
	fileEditor: {
		/**
		 * C​r​e​a​t​e​ ​f​i​l​e
		 */
		createFile: string
		/**
		 * E​d​i​t​ ​f​i​l​e
		 */
		editFile: string
		/**
		 * U​n​t​i​t​l​e​d
		 */
		untitled: string
		/**
		 * T​i​t​l​e
		 */
		title: string
		/**
		 * B​o​d​y
		 */
		body: string
		/**
		 * F​i​l​e​ ​t​i​t​l​e
		 */
		fileTitlePlaceholder: string
		/**
		 * W​r​i​t​e​ ​m​a​r​k​d​o​w​n​.​.​.
		 */
		bodyPlaceholder: string
		/**
		 * C​t​r​l​+​S​ ​t​o​ ​s​a​v​e​ ​/​ ​C​t​r​l​+​S​h​i​f​t​+​S​ ​t​o​ ​s​a​v​e​ ​a​n​d​ ​c​l​o​s​e
		 */
		shortcutsHint: string
		/**
		 * S​a​v​i​n​g​.​.​.
		 */
		saving: string
		/**
		 * T​i​t​l​e​ ​i​s​ ​r​e​q​u​i​r​e​d
		 */
		titleRequired: string
		/**
		 * F​i​l​e​ ​p​a​t​h​ ​i​s​ ​m​i​s​s​i​n​g
		 */
		filePathMissing: string
		/**
		 * N​o​ ​c​h​a​n​g​e​s
		 */
		noChanges: string
		/**
		 * F​i​l​e​ ​s​a​v​e​d
		 */
		fileSaved: string
		/**
		 * A​ ​f​i​l​e​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​ ​a​t​ ​t​h​a​t​ ​p​a​t​h​:​ ​{​p​a​t​h​}
		 * @param {unknown} path
		 */
		fileAlreadyExists: RequiredParams<'path'>
		gjson: {
			/**
			 * I​t​e​m​s
			 */
			items: string
			/**
			 * A​d​d​ ​i​t​e​m
			 */
			addItem: string
			/**
			 * U​n​t​i​t​l​e​d
			 */
			untitledItem: string
			/**
			 * R​e​m​o​v​e​ ​i​t​e​m
			 */
			removeItem: string
			/**
			 * E​a​c​h​ ​.​g​j​s​o​n​ ​i​t​e​m​ ​n​e​e​d​s​ ​a​ ​t​i​t​l​e​.
			 */
			missingItemTitle: string
			fields: {
				/**
				 * T​i​t​l​e
				 */
				title: string
				/**
				 * U​R​L
				 */
				url: string
				/**
				 * D​e​s​c​r​i​p​t​i​o​n
				 */
				desc: string
				/**
				 * C​o​m​m​a​n​d
				 */
				command: string
				/**
				 * T​a​g​s
				 */
				tags: string
				/**
				 * A​l​i​a​s​e​s
				 */
				aliases: string
				/**
				 * D​e​f​a​u​l​t​ ​a​c​t​i​o​n
				 */
				defaultAction: string
			}
			placeholders: {
				/**
				 * r​u​s​t​,​ ​d​o​c​s
				 */
				tags: string
				/**
				 * b​o​o​k​,​ ​r​u​s​t​b​o​o​k
				 */
				aliases: string
			}
			defaultActionOptions: {
				/**
				 * A​u​t​o
				 */
				auto: string
				/**
				 * C​o​m​m​a​n​d
				 */
				command: string
				/**
				 * U​R​L
				 */
				url: string
			}
		}
	}
	markdownPreview: {
		/**
		 * C​o​p​i​e​d​ ​c​o​d​e​ ​b​l​o​c​k​ ​#​{​i​n​d​e​x​}
		 * @param {unknown} index
		 */
		copiedCodeBlock: RequiredParams<'index'>
		/**
		 * C​o​d​e​ ​b​l​o​c​k​ ​#​{​i​n​d​e​x​}​ ​n​o​t​ ​f​o​u​n​d
		 * @param {unknown} index
		 */
		codeBlockNotFound: RequiredParams<'index'>
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​c​o​p​y​ ​c​o​d​e​ ​b​l​o​c​k​:​ ​{​e​r​r​o​r​}
		 * @param {unknown} error
		 */
		copyCodeBlockFailed: RequiredParams<'error'>
		/**
		 * S​o​u​r​c​e​ ​f​i​l​e​ ​n​o​t​ ​f​o​u​n​d
		 */
		sourceFileNotFound: string
		/**
		 * T​a​s​k​ ​n​o​t​ ​f​o​u​n​d
		 */
		taskNotFound: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​t​a​s​k​:​ ​{​e​r​r​o​r​}
		 * @param {unknown} error
		 */
		updateTaskFailed: RequiredParams<'error'>
	}
	tagCloudPage: {
		/**
		 * T​a​g​ ​C​l​o​u​d
		 */
		title: string
		/**
		 * {​c​o​u​n​t​}​ ​t​a​g​s
		 * @param {unknown} count
		 */
		tags: RequiredParams<'count'>
		/**
		 * {​c​o​u​n​t​}​ ​t​a​g​ ​a​s​s​i​g​n​m​e​n​t​s
		 * @param {unknown} count
		 */
		tagAssignments: RequiredParams<'count'>
		/**
		 * S​o​r​t​ ​b​y​ ​n​a​m​e
		 */
		sortByName: string
		/**
		 * S​o​r​t​ ​b​y​ ​c​o​u​n​t
		 */
		sortByCount: string
		/**
		 * F​i​l​t​e​r​ ​t​a​g​s
		 */
		filterPlaceholder: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​l​o​a​d​ ​t​a​g​s​:​ ​{​e​r​r​o​r​}
		 * @param {unknown} error
		 */
		loadError: RequiredParams<'error'>
		/**
		 * S​e​a​r​c​h​ ​#​{​t​a​g​}
		 * @param {unknown} tag
		 */
		searchTag: RequiredParams<'tag'>
		/**
		 * N​o​ ​t​a​g​s​ ​f​o​u​n​d​.
		 */
		empty: string
	}
}

export type TranslationFunctions = {
	previewPanel: {
		notFound: {
			/**
			 * Not Found
			 */
			title: () => LocalizedString
			/**
			 * No matching files in your dictionaries.
			 */
			description: () => LocalizedString
		}
		/**
		 * Unknown preview type: {type}
		 */
		unknownPreviewType: (arg: { type: unknown }) => LocalizedString
		/**
		 * DEBOUNCING...
		 */
		debouncing: () => LocalizedString
		/**
		 * Open link
		 */
		openLink: () => LocalizedString
		/**
		 * Inspect item
		 */
		inspectItem: () => LocalizedString
		/**
		 * toggle View Mode
		 */
		toggleViewMode: () => LocalizedString
		/**
		 * Copy Main Content
		 */
		copyContent: () => LocalizedString
		/**
		 * Open Help
		 */
		openHelp: () => LocalizedString
		/**
		 * Open settings.json
		 */
		openSettingsFile: () => LocalizedString
		/**
		 * Load
		 */
		loadHtmlPreview: () => LocalizedString
		/**
		 * Loaded
		 */
		loadedHtmlPreview: () => LocalizedString
		/**
		 * Open
		 */
		openHtmlPreview: () => LocalizedString
		/**
		 * Text copied to clipboard
		 */
		textCopied: () => LocalizedString
		/**
		 * No text to copy
		 */
		noTextToCopy: () => LocalizedString
		/**
		 * No source file path.
		 */
		noSourceFilePath: () => LocalizedString
		/**
		 * Failed to open file. Opened containing folder instead.
		 */
		openFileFallback: () => LocalizedString
	}
	searchBar: {
		/**
		 * Search...
		 */
		placeholder: () => LocalizedString
		/**
		 * Full scan
		 */
		fullScan: () => LocalizedString
		/**
		 * Index refreshed
		 */
		indexRefreshed: () => LocalizedString
		/**
		 * Failed to refresh index
		 */
		refreshIndexFailed: () => LocalizedString
	}
	itemList: {
		/**
		 * Searching...
		 */
		searching: () => LocalizedString
		/**
		 * Scanning your dictionary
		 */
		scanningDictionary: () => LocalizedString
		/**
		 * No results found
		 */
		noResults: () => LocalizedString
		/**
		 * Try different keywords or check your spelling.
		 */
		noResultsHint: () => LocalizedString
		/**
		 * Today
		 */
		today: () => LocalizedString
		/**
		 * Yesterday
		 */
		yesterday: () => LocalizedString
		/**
		 * {count} days ago
		 */
		daysAgo: (arg: { count: unknown }) => LocalizedString
		snippetSources: {
			/**
			 * Body
			 */
			body: () => LocalizedString
			/**
			 * Title
			 */
			title: () => LocalizedString
			/**
			 * Alias
			 */
			alias: () => LocalizedString
			/**
			 * Tag
			 */
			tag: () => LocalizedString
		}
	}
	common: {
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Reload
		 */
		reload: () => LocalizedString
		/**
		 * Command
		 */
		command: () => LocalizedString
		/**
		 * Description
		 */
		description: () => LocalizedString
	}
	appMessages: {
		/**
		 * Failed to reload themes.
		 */
		failedReloadThemes: () => LocalizedString
		/**
		 * Failed to refresh saved file: {error}
		 */
		failedRefreshSavedFile: (arg: { error: unknown }) => LocalizedString
		/**
		 * Failed to read file: {error}
		 */
		failedReadFile: (arg: { error: unknown }) => LocalizedString
		/**
		 * No target groups configured
		 */
		noTargetGroupsConfigured: () => LocalizedString
		/**
		 * No other active target groups to switch to.
		 */
		noOtherActiveTargetGroups: () => LocalizedString
		/**
		 * Switched target group: {name}
		 */
		switchedTargetGroup: (arg: { name: unknown }) => LocalizedString
		/**
		 * Failed to switch target group: {error}
		 */
		switchTargetGroupFailed: (arg: { error: unknown }) => LocalizedString
		/**
		 * Ran: {title}
		 */
		ranItem: (arg: { title: unknown }) => LocalizedString
		/**
		 * Launched: {title}
		 */
		launchedItem: (arg: { title: unknown }) => LocalizedString
		/**
		 * Failed to open containing folder: {error}
		 */
		openContainingFolderFailed: (arg: { error: unknown }) => LocalizedString
		/**
		 * Failed to copy text: {error}
		 */
		copyTextFailed: (arg: { error: unknown }) => LocalizedString
	}
	statusBar: {
		/**
		 * {count} items shown
		 */
		indexedItems: (arg: { count: unknown }) => LocalizedString
		/**
		 * Target
		 */
		target: () => LocalizedString
		/**
		 * Switch Target
		 */
		switchTarget: () => LocalizedString
		/**
		 * Warm
		 */
		startupWarm: () => LocalizedString
		/**
		 * {name} {completed}/{total}
		 */
		startupWarmRunning: (arg: { completed: unknown, name: unknown, total: unknown }) => LocalizedString
	}
	queryInspector: {
		/**
		 * Query Inspector
		 */
		title: () => LocalizedString
	}
	itemInspector: {
		/**
		 * Item Inspector
		 */
		title: () => LocalizedString
	}
	aboutPage: {
		/**
		 * about Glimpse
		 */
		title: () => LocalizedString
		/**
		 * Local-first search and command launcher.
		 */
		subtitle: () => LocalizedString
		overview: {
			/**
			 * Overview
			 */
			title: () => LocalizedString
			/**
			 * Glimpse is a lightweight launcher for searching local dictionaries, opening references, and running trusted commands.
			 */
			description1: () => LocalizedString
			/**
			 * It is designed around fast keyboard navigation, local-first indexing, and simple Markdown / JSON based content.
			 */
			description2: () => LocalizedString
			/**
			 * GitHub Homepage
			 */
			githubHomepage: () => LocalizedString
			/**
			 * Report Issue
			 */
			reportIssue: () => LocalizedString
		}
		/**
		 * Application
		 */
		application: () => LocalizedString
		/**
		 * Technical Details
		 */
		technicalDetails: () => LocalizedString
		/**
		 * Features
		 */
		features: () => LocalizedString
		labels: {
			/**
			 * Name
			 */
			name: () => LocalizedString
			/**
			 * Version
			 */
			version: () => LocalizedString
			/**
			 * Build
			 */
			build: () => LocalizedString
			/**
			 * License
			 */
			license: () => LocalizedString
			/**
			 * Frontend
			 */
			frontend: () => LocalizedString
			/**
			 * Desktop runtime
			 */
			desktopRuntime: () => LocalizedString
			/**
			 * Search engine
			 */
			searchEngine: () => LocalizedString
			/**
			 * Index formats
			 */
			indexFormats: () => LocalizedString
			/**
			 * Command execution
			 */
			commandExecution: () => LocalizedString
			/**
			 * Security
			 */
			security: () => LocalizedString
		}
	}
	convertPage: {
		/**
		 * convert
		 */
		title: () => LocalizedString
		/**
		 * Type {command} and press Enter.
		 */
		description: (arg: { command: unknown }) => LocalizedString
		/**
		 * Supported for now: length, weight, temperature, data size, and time.
		 */
		help: () => LocalizedString
		errors: {
			/**
			 * Unsupported conversion
			 */
			unsupportedConversion: () => LocalizedString
			/**
			 * Unsupported unit
			 */
			unsupportedUnit: () => LocalizedString
			/**
			 * Incompatible units
			 */
			incompatibleUnits: () => LocalizedString
		}
		dialog: {
			/**
			 * Unit Converter
			 */
			title: () => LocalizedString
			/**
			 * Convert values between different units.
			 */
			description: () => LocalizedString
			/**
			 * Examples
			 */
			examples: () => LocalizedString
			/**
			 * Commands
			 */
			commandsTitle: () => LocalizedString
			commands: {
				/**
				 * Millimeter
				 */
				mm: () => LocalizedString
				/**
				 * Centimeter
				 */
				cm: () => LocalizedString
			}
		}
	}
	datePage: {
		/**
		 * date
		 */
		title: () => LocalizedString
		/**
		 * Type {command} and press Enter.
		 */
		description: (arg: { command: unknown }) => LocalizedString
		/**
		 * Supported for now: today, today + 7d, today - 7d.
		 */
		help: () => LocalizedString
		errors: {
			/**
			 * Unsupported date expression
			 */
			unsupportedExpression: () => LocalizedString
		}
		dialog: {
			/**
			 * Date Calculator
			 */
			title: () => LocalizedString
			/**
			 * Perform date calculations by adding or subtracting days.
			 */
			description: () => LocalizedString
			/**
			 * Examples
			 */
			examples: () => LocalizedString
			/**
			 * Commands
			 */
			commandsTitle: () => LocalizedString
			commands: {
				/**
				 * Today's date
				 */
				today: () => LocalizedString
			}
		}
	}
	numericPage: {
		/**
		 * calculator
		 */
		title: () => LocalizedString
		/**
		 * Type {command} and press Enter.
		 */
		description: (arg: { command: unknown }) => LocalizedString
		/**
		 * Supported: arithmetic, sqrt, pow, abs, round, floor, ceil, min, max, pi, and e.
		 */
		help: () => LocalizedString
		errors: {
			/**
			 * import is disabled
			 */
			importDisabled: () => LocalizedString
			/**
			 * createUnit is disabled
			 */
			createUnitDisabled: () => LocalizedString
			/**
			 * Invalid result
			 */
			invalidResult: () => LocalizedString
		}
		dialog: {
			/**
			 * Calculator
			 */
			title: () => LocalizedString
			/**
			 * Enter a mathematical expression and press Enter to calculate the result.
			 */
			description: () => LocalizedString
			/**
			 * Examples
			 */
			examples: () => LocalizedString
			/**
			 * Commands
			 */
			commandsTitle: () => LocalizedString
			commands: {
				/**
				 * Absolute value
				 */
				abs: () => LocalizedString
				/**
				 * Square root
				 */
				sqrt: () => LocalizedString
				/**
				 * Pi
				 */
				pi: () => LocalizedString
			}
		}
	}
	debugPage: {
		/**
		 * debug
		 */
		title: () => LocalizedString
		/**
		 * Internal diagnostics.
		 */
		subtitle: () => LocalizedString
		/**
		 * Loading debug data...
		 */
		loading: () => LocalizedString
		/**
		 * Failed to load debug data: {error}
		 */
		loadError: (arg: { error: unknown }) => LocalizedString
		sections: {
			/**
			 * Index
			 */
			index: () => LocalizedString
			/**
			 * Preview types
			 */
			previewTypes: () => LocalizedString
			/**
			 * Open actions
			 */
			openActions: () => LocalizedString
			/**
			 * Indexer
			 */
			indexer: () => LocalizedString
			/**
			 * Filters
			 */
			filters: () => LocalizedString
			/**
			 * Ignore patterns
			 */
			ignorePatterns: () => LocalizedString
			/**
			 * Command execution logs
			 */
			commandExecutionLogs: () => LocalizedString
		}
		labels: {
			/**
			 * Total items
			 */
			totalItems: () => LocalizedString
			/**
			 * Starred items
			 */
			starItems: () => LocalizedString
			/**
			 * Tagged items
			 */
			taggedItems: () => LocalizedString
			/**
			 * Alias items
			 */
			aliasItems: () => LocalizedString
			/**
			 * Markdown
			 */
			markdown: () => LocalizedString
			/**
			 * Raw
			 */
			raw: () => LocalizedString
			/**
			 * External
			 */
			external: () => LocalizedString
			/**
			 * Command items
			 */
			commandItems: () => LocalizedString
			/**
			 * External open items
			 */
			externalOpenItems: () => LocalizedString
			/**
			 * Indexed items
			 */
			indexedItems: () => LocalizedString
			/**
			 * Watch status
			 */
			watchStatus: () => LocalizedString
			/**
			 * Last scan
			 */
			lastScan: () => LocalizedString
			/**
			 * Startup warm
			 */
			startupWarmStatus: () => LocalizedString
			/**
			 * Current warm target
			 */
			startupWarmCurrent: () => LocalizedString
			/**
			 * Warm progress
			 */
			startupWarmProgress: () => LocalizedString
			/**
			 * Warm error
			 */
			startupWarmError: () => LocalizedString
			/**
			 * Ignore hidden files
			 */
			ignoreHiddenFiles: () => LocalizedString
			/**
			 * Max file size
			 */
			maxFileSize: () => LocalizedString
		}
		values: {
			/**
			 * N/A
			 */
			notAvailable: () => LocalizedString
			/**
			 * Unlimited
			 */
			unlimited: () => LocalizedString
			/**
			 * {value} bytes
			 */
			bytes: (arg: { value: unknown }) => LocalizedString
		}
		messages: {
			/**
			 * No ignore patterns
			 */
			noIgnorePatterns: () => LocalizedString
			/**
			 * No command logs
			 */
			noCommandLogs: () => LocalizedString
			/**
			 * details
			 */
			details: () => LocalizedString
			/**
			 * Open logs folder
			 */
			openLogsFolder: () => LocalizedString
		}
	}
	commandHistoryPage: {
		/**
		 * Command History
		 */
		title: () => LocalizedString
		/**
		 * No command history yet.
		 */
		empty: () => LocalizedString
		/**
		 * Copy command result
		 */
		copyResult: () => LocalizedString
		/**
		 * Details
		 */
		details: () => LocalizedString
		/**
		 * Target
		 */
		target: () => LocalizedString
		/**
		 * Input
		 */
		input: () => LocalizedString
		status: {
			/**
			 * Success
			 */
			success: () => LocalizedString
			/**
			 * Error
			 */
			error: () => LocalizedString
		}
		kind: {
			/**
			 * Command
			 */
			command: () => LocalizedString
			/**
			 * Page action
			 */
			pageAction: () => LocalizedString
			/**
			 * Plugin action
			 */
			pluginAction: () => LocalizedString
		}
	}
	shortcutsPage: {
		/**
		 * keyboard shortcuts
		 */
		title: () => LocalizedString
		/**
		 * Currently available keyboard shortcuts in Glimpse.
		 */
		subtitle: () => LocalizedString
		groups: {
			/**
			 * Search
			 */
			search: () => LocalizedString
			/**
			 * Navigation
			 */
			navigation: () => LocalizedString
			/**
			 * Files
			 */
			files: () => LocalizedString
			/**
			 * Preview
			 */
			preview: () => LocalizedString
			/**
			 * Code copy
			 */
			codeCopy: () => LocalizedString
			/**
			 * View
			 */
			view: () => LocalizedString
			/**
			 * Internal
			 */
			internal: () => LocalizedString
			/**
			 * Plugin
			 */
			plugin: () => LocalizedString
		}
		actions: {
			/**
			 * Focus search
			 */
			focusSearch: () => LocalizedString
			/**
			 * Toggle hidden filter
			 */
			toggleHiddenFilter: () => LocalizedString
			toggleUnstarFilter: () => LocalizedString
			/**
			 * Toggle reverse order
			 */
			toggleReverseSearch: () => LocalizedString
			/**
			 * Toggle internal search
			 */
			toggleInternalFilter: () => LocalizedString
			/**
			 * Toggle plugin playground search
			 */
			togglePluginPlaygroundFilter: () => LocalizedString
			/**
			 * Move selection down
			 */
			moveDown: () => LocalizedString
			/**
			 * Move selection up
			 */
			moveUp: () => LocalizedString
			/**
			 * Open selected item
			 */
			openSelected: () => LocalizedString
			/**
			 * Reveal selected item
			 */
			revealSelected: () => LocalizedString
			/**
			 * Scroll preview down
			 */
			scrollPreviewDown: () => LocalizedString
			/**
			 * Scroll preview up
			 */
			scrollPreviewUp: () => LocalizedString
			/**
			 * Pin current preview
			 */
			pinPreview: () => LocalizedString
			/**
			 * Next preview tab
			 */
			nextPreviewTab: () => LocalizedString
			/**
			 * Previous preview tab
			 */
			previousPreviewTab: () => LocalizedString
			/**
			 * Close preview tab
			 */
			closePreviewTab: () => LocalizedString
			/**
			 * Toggle Markdown / Raw
			 */
			togglePreviewMode: () => LocalizedString
			/**
			 * Toggle sidebar
			 */
			toggleSidebar: () => LocalizedString
			/**
			 * Toggle compact mode
			 */
			toggleCompactMode: () => LocalizedString
			/**
			 * Switch target group
			 */
			switchTargetGroup: () => LocalizedString
			/**
			 * Open query inspector
			 */
			openQueryInspector: () => LocalizedString
			/**
			 * Open help for the current page
			 */
			openItemHelp: () => LocalizedString
			/**
			 * Open Help
			 */
			openHelp: () => LocalizedString
			/**
			 * Move down by page
			 */
			moveDownPage: () => LocalizedString
			/**
			 * Move up by page
			 */
			moveUpPage: () => LocalizedString
			/**
			 * Open source file
			 */
			openSourceFile: () => LocalizedString
			/**
			 * Reveal source directory
			 */
			revealSourceDirectory: () => LocalizedString
			/**
			 * Create file
			 */
			createFile: () => LocalizedString
			/**
			 * Edit active page
			 */
			editActivePage: () => LocalizedString
			/**
			 * Close preview
			 */
			closePreview: () => LocalizedString
			/**
			 * Copy code block #{index}
			 */
			copyCodeBlock: (arg: { index: unknown }) => LocalizedString
			/**
			 * Show / hide window
			 */
			showHideWindow: () => LocalizedString
			/**
			 * Open settings.json
			 */
			openSettingsFile: () => LocalizedString
			/**
			 * Copy preview content
			 */
			copyPreviewContent: () => LocalizedString
		}
		messages: {
			/**
			 * Loading shortcuts...
			 */
			loading: () => LocalizedString
			/**
			 * Failed to update shortcuts
			 */
			failedToUpdate: () => LocalizedString
			/**
			 * Remove shortcut
			 */
			removeShortcut: () => LocalizedString
			/**
			 * Add shortcut
			 */
			addShortcut: () => LocalizedString
			/**
			 * Press shortcut
			 */
			pressShortcut: () => LocalizedString
		}
	}
	pluginPage: {
		/**
		 * Plugin Page
		 */
		title: () => LocalizedString
		/**
		 * Manage installed Glimpse plugins and their Internal Page contributions.
		 */
		subtitle: () => LocalizedString
		sections: {
			/**
			 * Installed Plugins
			 */
			installedPlugins: () => LocalizedString
			/**
			 * Plugin Model
			 */
			pluginModel: () => LocalizedString
			/**
			 * Capabilities
			 */
			capabilities: () => LocalizedString
			/**
			 * Feature Pages
			 */
			featurePages: () => LocalizedString
		}
		installed: {
			/**
			 * {enabled} of {total} enabled
			 */
			enabledSummary: (arg: { enabled: unknown, total: unknown }) => LocalizedString
			/**
			 * Loaded from config plugins
			 */
			loadedFromConfig: () => LocalizedString
			/**
			 * Failed to load plugins: {error}
			 */
			loadError: (arg: { error: unknown }) => LocalizedString
			/**
			 * No plugins found.
			 */
			empty: () => LocalizedString
			/**
			 * Local plugin folder path, one per line
			 */
			installPlaceholder: () => LocalizedString
			/**
			 * Drop one or more local plugin folders here, or paste paths below.
			 */
			installDropHint: () => LocalizedString
			/**
			 * If manifest.json has the same id as an installed plugin, it will be replaced automatically.
			 */
			installReplaceHint: () => LocalizedString
			/**
			 * Replace
			 */
			replace: () => LocalizedString
			/**
			 * Install
			 */
			install: () => LocalizedString
			/**
			 * Installing
			 */
			installing: () => LocalizedString
			/**
			 * Open folder
			 */
			openFolder: () => LocalizedString
			/**
			 * Installed {pluginId}. Trust it before enabling.
			 */
			installSuccess: (arg: { pluginId: unknown }) => LocalizedString
			/**
			 * Install failed: {error}
			 */
			installFailed: (arg: { error: unknown }) => LocalizedString
			/**
			 * Search installed plugins
			 */
			searchPlaceholder: () => LocalizedString
			/**
			 * No matching plugins found.
			 */
			noSearchResults: () => LocalizedString
			/**
			 * Reload all
			 */
			reloadAll: () => LocalizedString
		}
		pluginModel: {
			'package': {
				/**
				 * Package
				 */
				label: () => LocalizedString
				/**
				 * Distribution unit
				 */
				value: () => LocalizedString
			}
			capability: {
				/**
				 * Capability
				 */
				label: () => LocalizedString
				/**
				 * Viewer, extractor, thumbnailer, block, template
				 */
				value: () => LocalizedString
			}
			runtime: {
				/**
				 * Runtime
				 */
				label: () => LocalizedString
				/**
				 * frontend, worker
				 */
				value: () => LocalizedString
			}
			permissionScope: {
				/**
				 * Permission scope
				 */
				label: () => LocalizedString
				/**
				 * Capability-level declarations
				 */
				value: () => LocalizedString
			}
		}
		capabilities: {
			viewer: {
				/**
				 * Viewer
				 */
				name: () => LocalizedString
				/**
				 * Render files such as PDF, audio, video, and Office previews.
				 */
				description: () => LocalizedString
			}
			extractor: {
				/**
				 * Extractor
				 */
				name: () => LocalizedString
				/**
				 * Extract text, metadata, chapters, captions, and searchable content.
				 */
				description: () => LocalizedString
			}
			thumbnailer: {
				/**
				 * Thumbnailer
				 */
				name: () => LocalizedString
				/**
				 * Generate cover images, page thumbnails, video keyframes, and waveforms.
				 */
				description: () => LocalizedString
			}
			pageBlock: {
				/**
				 * Page Block
				 */
				name: () => LocalizedString
				/**
				 * Provide reusable blocks for user-created feature pages.
				 */
				description: () => LocalizedString
			}
			featureTemplate: {
				/**
				 * Feature Template
				 */
				name: () => LocalizedString
				/**
				 * Seed custom pages such as collections, playlists, and document hubs.
				 */
				description: () => LocalizedString
			}
		}
		featurePages: {
			/**
			 * Feature pages are owned by Core, while plugins contribute page blocks and templates. This keeps custom pages composable without giving every plugin full control over the entire page.
			 */
			description: () => LocalizedString
		}
		pluginRow: {
			/**
			 * {count} Internal Pages
			 */
			internalPageCount: (arg: { count: unknown }) => LocalizedString
			/**
			 * Enabled
			 */
			enabled: () => LocalizedString
			/**
			 * Disabled
			 */
			disabled: () => LocalizedString
			/**
			 * Trusted
			 */
			trusted: () => LocalizedString
			/**
			 * Untrusted
			 */
			untrusted: () => LocalizedString
			/**
			 * This plugin must be trusted before Glimpse can load its code.
			 */
			trustRequired: () => LocalizedString
			/**
			 * Trust
			 */
			trust: () => LocalizedString
			/**
			 * Revoke Trust
			 */
			revokeTrust: () => LocalizedString
			/**
			 * Updating Trust
			 */
			trusting: () => LocalizedString
			/**
			 * Uninstall
			 */
			uninstall: () => LocalizedString
			/**
			 * Uninstalling
			 */
			uninstalling: () => LocalizedString
			/**
			 * Uninstall {name}? This removes the installed plugin directory.
			 */
			uninstallConfirm: (arg: { name: unknown }) => LocalizedString
			/**
			 * Uninstalled {pluginId}.
			 */
			uninstallSuccess: (arg: { pluginId: unknown }) => LocalizedString
			/**
			 * Uninstall failed: {error}
			 */
			uninstallFailed: (arg: { error: unknown }) => LocalizedString
			/**
			 * ON
			 */
			on: () => LocalizedString
			/**
			 * OFF
			 */
			off: () => LocalizedString
			/**
			 * Toggle {name}
			 */
			toggleLabel: (arg: { name: unknown }) => LocalizedString
		}
	}
	settingsPage: {
		/**
		 * settings
		 */
		title: () => LocalizedString
		/**
		 * Configure Glimpse behavior.
		 */
		subtitle: () => LocalizedString
		appearance: {
			/**
			 * Appearance
			 */
			title: () => LocalizedString
			/**
			 * Change the visual appearance of Glimpse.
			 */
			description: () => LocalizedString
			/**
			 * No custom themes found.
			 */
			noCustomThemes: () => LocalizedString
			/**
			 * Open themes folder
			 */
			openThemesFolder: () => LocalizedString
			/**
			 * Reload themes
			 */
			reloadThemes: () => LocalizedString
			/**
			 * Select theme
			 */
			selectTheme: () => LocalizedString
			/**
			 * No theme selected
			 */
			noThemeSelected: () => LocalizedString
			/**
			 * Search theme...
			 */
			searchTheme: () => LocalizedString
			/**
			 * No themes found.
			 */
			noThemesFound: () => LocalizedString
			/**
			 * Built-in
			 */
			builtInTheme: () => LocalizedString
			/**
			 * Custom
			 */
			customTheme: () => LocalizedString
		}
		targetGroups: {
			/**
			 * Target Groups
			 */
			title: () => LocalizedString
			/**
			 * Manage search target directories.
			 */
			description: () => LocalizedString
			/**
			 * Create target group
			 */
			create: () => LocalizedString
			/**
			 * Edit target group
			 */
			edit: () => LocalizedString
			/**
			 * No target groups configured.
			 */
			none: () => LocalizedString
			/**
			 * Add group
			 */
			addGroup: () => LocalizedString
			/**
			 * Add a target group to manage search paths.
			 */
			addHint: () => LocalizedString
			/**
			 * Target group name
			 */
			targetGroupName: () => LocalizedString
			/**
			 * Active
			 */
			active: () => LocalizedString
			/**
			 * Inactive
			 */
			inactive: () => LocalizedString
			/**
			 * Current
			 */
			current: () => LocalizedString
			/**
			 * Make current
			 */
			makeCurrent: () => LocalizedString
			/**
			 * Include {name} in the Ctrl+R cycle
			 */
			activeToggle: (arg: { name: unknown }) => LocalizedString
			/**
			 * Remove target group
			 */
			removeTargetGroup: () => LocalizedString
			/**
			 * Type a path and press Enter
			 */
			addPathPlaceholder: () => LocalizedString
			/**
			 * Select folder
			 */
			addPath: () => LocalizedString
			/**
			 * No paths
			 */
			noPaths: () => LocalizedString
			/**
			 * Path for {name}
			 */
			pathFor: (arg: { name: unknown }) => LocalizedString
			/**
			 * Remove path
			 */
			removePath: () => LocalizedString
		}
		ui: {
			/**
			 * UI
			 */
			title: () => LocalizedString
			/**
			 * Adjust interface density and layout.
			 */
			description: () => LocalizedString
			/**
			 * Compact list items
			 */
			compactListItems: () => LocalizedString
			/**
			 * Show denser search result rows.
			 */
			compactListItemsDescription: () => LocalizedString
			/**
			 * Close to tray
			 */
			closeToTray: () => LocalizedString
			/**
			 * Hide Glimpse to the system tray when the main window is closed.
			 */
			closeToTrayDescription: () => LocalizedString
			/**
			 * Language
			 */
			language: () => LocalizedString
			/**
			 * Change the interface language.
			 */
			languageDescription: () => LocalizedString
		}
		experimental: {
			/**
			 * Experimental
			 */
			title: () => LocalizedString
			/**
			 * Try features that may depend on app and OS behavior.
			 */
			description: () => LocalizedString
			/**
			 * Use selected text as query
			 */
			captureSelectedTextOnActivation: () => LocalizedString
			/**
			 * When Glimpse is opened from another app, read the selected text and put it in the search box.
			 */
			captureSelectedTextOnActivationDescription: () => LocalizedString
		}
		security: {
			/**
			 * Security
			 */
			title: () => LocalizedString
			/**
			 * Control which command items are allowed to run.
			 */
			description: () => LocalizedString
			/**
			 * Command Policy
			 */
			commandPolicy: () => LocalizedString
			/**
			 * Choose how Glimpse decides which commands can run.
			 */
			commandPolicyDescription: () => LocalizedString
			/**
			 * Whitelist Commands
			 */
			whitelistCommands: () => LocalizedString
			/**
			 * Allowed commands when policy mode is whitelist.
			 */
			whitelistDescription: () => LocalizedString
			/**
			 * Blacklist Commands
			 */
			blacklistCommands: () => LocalizedString
			/**
			 * Blocked commands when policy mode is blacklist.
			 */
			blacklistDescription: () => LocalizedString
			/**
			 * Add
			 */
			add: () => LocalizedString
			/**
			 * No commands
			 */
			noCommands: () => LocalizedString
		}
		advanced: {
			/**
			 * Advanced
			 */
			title: () => LocalizedString
			/**
			 * Open the raw settings file.
			 */
			description: () => LocalizedString
			/**
			 * Open settings.json
			 */
			openSettings: () => LocalizedString
		}
		messages: {
			/**
			 * Target group names may contain only letters, numbers, spaces, '-' and '_'.
			 */
			invalidTargetGroupName: () => LocalizedString
			/**
			 * A target group with this name already exists.
			 */
			duplicateTargetGroupName: () => LocalizedString
			/**
			 * Failed to add the target group.
			 */
			addTargetGroupFailed: () => LocalizedString
			/**
			 * Failed to rename the target group.
			 */
			renameTargetGroupFailed: () => LocalizedString
			/**
			 * Failed to remove the target group.
			 */
			removeTargetGroupFailed: () => LocalizedString
			/**
			 * The current target group cannot be inactive.
			 */
			currentTargetGroupMustBeActive: () => LocalizedString
			/**
			 * Failed to update the target group active state.
			 */
			updateTargetGroupActiveFailed: () => LocalizedString
			/**
			 * Failed to make this target group current.
			 */
			makeCurrentTargetGroupFailed: () => LocalizedString
			/**
			 * This path is already registered.
			 */
			duplicateTargetPath: () => LocalizedString
			/**
			 * Failed to add the target path.
			 */
			addTargetPathFailed: () => LocalizedString
			/**
			 * The target path cannot be empty.
			 */
			emptyTargetPath: () => LocalizedString
			/**
			 * Failed to update the target path.
			 */
			updateTargetPathFailed: () => LocalizedString
			/**
			 * Failed to remove the target path.
			 */
			removeTargetPathFailed: () => LocalizedString
		}
	}
	helpPage: {
		/**
		 * Help
		 */
		title: () => LocalizedString
		/**
		 * Quick reference for Glimpse search, target groups, and internal pages.
		 */
		description: () => LocalizedString
		groups: {
			/**
			 * Search, target groups, and internal pages
			 */
			usage: () => LocalizedString
		}
		search: {
			/**
			 * Search
			 */
			title: () => LocalizedString
			/**
			 * Search indexed items using keywords.
			 */
			description: () => LocalizedString
			/**
			 * Search the current target group
			 */
			currentGroup: () => LocalizedString
			/**
			 * Filter by tag
			 */
			tag: () => LocalizedString
			/**
			 * Exclude starred items from results
			 */
			unstar: () => LocalizedString
			/**
			 * Search hidden items in the current target group
			 */
			hidden: () => LocalizedString
			/**
			 * Show older items first
			 */
			reverse: () => LocalizedString
			/**
			 * Search Glimpse internal pages
			 */
			internal: () => LocalizedString
			/**
			 * Search plugin playground pages
			 */
			pluginPlayground: () => LocalizedString
			/**
			 * Search all target groups
			 */
			global: () => LocalizedString
			/**
			 * Pass arguments to the selected command item
			 */
			commandArgs: () => LocalizedString
		}
		open: {
			/**
			 * open
			 */
			title: () => LocalizedString
			/**
			 * Open source file
			 */
			file: () => LocalizedString
			/**
			 * Open external URL
			 */
			url: () => LocalizedString
			/**
			 * Run command
			 */
			command: () => LocalizedString
			/**
			 * Command path
			 */
			path: () => LocalizedString
			/**
			 * URL
			 */
			openUrl: () => LocalizedString
			/**
			 * Command path
			 */
			openCommand: () => LocalizedString
		}
		internalPages: {
			/**
			 * Internal Pages
			 */
			title: () => LocalizedString
			/**
			 * Open Help
			 */
			help: () => LocalizedString
			/**
			 * Open Settings
			 */
			settings: () => LocalizedString
			/**
			 * Open About
			 */
			about: () => LocalizedString
			/**
			 * Open Debug
			 */
			debug: () => LocalizedString
			/**
			 * Open Keyboard Shortcuts
			 */
			shortcuts: () => LocalizedString
			/**
			 * Open Metadata Help
			 */
			metadata: () => LocalizedString
			/**
			 * Open Command History
			 */
			commandHistory: () => LocalizedString
			/**
			 * Open Tag Cloud
			 */
			tagCloud: () => LocalizedString
			/**
			 * Open Plugins
			 */
			plugin: () => LocalizedString
		}
		targetGroups: {
			/**
			 * Target Groups
			 */
			title: () => LocalizedString
			/**
			 * The target group used by normal search
			 */
			current: () => LocalizedString
			/**
			 * Included in the Ctrl+R cycle
			 */
			active: () => LocalizedString
			/**
			 * Kept in settings but skipped by the Ctrl+R cycle
			 */
			inactive: () => LocalizedString
			/**
			 * Switch the current target group among active target groups
			 */
			'switch': () => LocalizedString
			/**
			 * Edit target groups and choose folders
			 */
			settings: () => LocalizedString
			/**
			 * Search all target groups
			 */
			globalSearch: () => LocalizedString
		}
		shortcuts: {
			/**
			 * Shortcuts
			 */
			title: () => LocalizedString
			/**
			 * Open or run the selected item
			 */
			open: () => LocalizedString
			/**
			 * Toggle the sidebar
			 */
			sidebar: () => LocalizedString
			/**
			 * Open Query Inspector
			 */
			inspector: () => LocalizedString
			/**
			 * Switch the current target group
			 */
			switchGroup: () => LocalizedString
		}
		more: {
			/**
			 * Learn More
			 */
			title: () => LocalizedString
			/**
			 * Use :shortcuts to view all keyboard shortcuts.
			 */
			shortcuts: () => LocalizedString
			/**
			 * Use :settings to view configuration options.
			 */
			settings: () => LocalizedString
			/**
			 * Use :metadata to view Markdown metadata and .gjson fields.
			 */
			metadata: () => LocalizedString
			/**
			 * Use :about to view version and technical information.
			 */
			about: () => LocalizedString
		}
	}
	metadataHelpPage: {
		/**
		 * Metadata
		 */
		title: () => LocalizedString
		/**
		 * Reference for Markdown frontmatter, .gjson indexes, command items, and open behavior.
		 */
		description: () => LocalizedString
		metadata: {
			/**
			 * Markdown Metadata
			 */
			title: () => LocalizedString
			/**
			 * Add a small YAML frontmatter block to the beginning of a Markdown file to control search metadata and open behavior.
			 */
			description: () => LocalizedString
			fields: {
				/**
				 * Title displayed in search results
				 */
				title: () => LocalizedString
				/**
				 * Search tags (multiple allowed)
				 */
				tags: () => LocalizedString
				/**
				 * Alternative names or abbreviations
				 */
				aliases: () => LocalizedString
				/**
				 * Prioritize this item in search results when true
				 */
				star: () => LocalizedString
				/**
				 * Hide from normal search and show only with ! search
				 */
				hidden: () => LocalizedString
				/**
				 * Run a command when pressing Enter
				 */
				commandOpenType: () => LocalizedString
				/**
				 * Open an external URL when pressing Enter
				 */
				externalOpenType: () => LocalizedString
				/**
				 * Command string used by command
				 */
				openPath: () => LocalizedString
				/**
				 * URL opened by url
				 */
				openUrl: () => LocalizedString
				/**
				 * Ignored by the Markdown metadata parser
				 */
				unknown: () => LocalizedString
			}
		}
		metadataExample: {
			/**
			 * Markdown Metadata Example
			 */
			title: () => LocalizedString
		}
		commands: {
			/**
			 * Commands
			 */
			title: () => LocalizedString
			/**
			 * Command items can receive everything after '>' in the search bar as command-line arguments. Commands are executed directly without using a shell.
			 */
			description: () => LocalizedString
			/**
			 * Commands are executed directly without using a shell.
			 */
			security: () => LocalizedString
			/**
			 * Run {command}
			 */
			runExample: (arg: { command: unknown }) => LocalizedString
		}
		jsonIndex: {
			/**
			 * .gjson Index
			 */
			title: () => LocalizedString
			/**
			 * A .gjson file can generate multiple searchable items from one JSON file.
			 */
			description: () => LocalizedString
			/**
			 * Only .gjson files use the multi-item JSON index parser
			 */
			extension: () => LocalizedString
			/**
			 * Treat the items array as searchable entries
			 */
			items: () => LocalizedString
			/**
			 * Use each item's title
			 */
			itemTitle: () => LocalizedString
			/**
			 * URL used for external preview and default Enter action
			 */
			itemUrl: () => LocalizedString
			/**
			 * Searchable description and Markdown preview text
			 */
			itemDesc: () => LocalizedString
			/**
			 * Tags used by #tag filtering
			 */
			metadataTags: () => LocalizedString
			/**
			 * Alternative searchable names
			 */
			metadataAliases: () => LocalizedString
			/**
			 * Prioritize this item in search results when true
			 */
			metadataStar: () => LocalizedString
			/**
			 * Hide from normal search and show only with ! search
			 */
			metadataHidden: () => LocalizedString
			/**
			 * When true, preview the URL in an iframe; when false, show Markdown text
			 */
			iframe: () => LocalizedString
			/**
			 * Optional Enter action override such as external URL or command path
			 */
			openOverride: () => LocalizedString
		}
		jsonExample: {
			/**
			 * .gjson Index Example
			 */
			title: () => LocalizedString
		}
	}
	fileEditor: {
		/**
		 * Create file
		 */
		createFile: () => LocalizedString
		/**
		 * Edit file
		 */
		editFile: () => LocalizedString
		/**
		 * Untitled
		 */
		untitled: () => LocalizedString
		/**
		 * Title
		 */
		title: () => LocalizedString
		/**
		 * Body
		 */
		body: () => LocalizedString
		/**
		 * File title
		 */
		fileTitlePlaceholder: () => LocalizedString
		/**
		 * Write markdown...
		 */
		bodyPlaceholder: () => LocalizedString
		/**
		 * Ctrl+S to save / Ctrl+Shift+S to save and close
		 */
		shortcutsHint: () => LocalizedString
		/**
		 * Saving...
		 */
		saving: () => LocalizedString
		/**
		 * Title is required
		 */
		titleRequired: () => LocalizedString
		/**
		 * File path is missing
		 */
		filePathMissing: () => LocalizedString
		/**
		 * No changes
		 */
		noChanges: () => LocalizedString
		/**
		 * File saved
		 */
		fileSaved: () => LocalizedString
		/**
		 * A file already exists at that path: {path}
		 */
		fileAlreadyExists: (arg: { path: unknown }) => LocalizedString
		gjson: {
			/**
			 * Items
			 */
			items: () => LocalizedString
			/**
			 * Add item
			 */
			addItem: () => LocalizedString
			/**
			 * Untitled
			 */
			untitledItem: () => LocalizedString
			/**
			 * Remove item
			 */
			removeItem: () => LocalizedString
			/**
			 * Each .gjson item needs a title.
			 */
			missingItemTitle: () => LocalizedString
			fields: {
				/**
				 * Title
				 */
				title: () => LocalizedString
				/**
				 * URL
				 */
				url: () => LocalizedString
				/**
				 * Description
				 */
				desc: () => LocalizedString
				/**
				 * Command
				 */
				command: () => LocalizedString
				/**
				 * Tags
				 */
				tags: () => LocalizedString
				/**
				 * Aliases
				 */
				aliases: () => LocalizedString
				/**
				 * Default action
				 */
				defaultAction: () => LocalizedString
			}
			placeholders: {
				/**
				 * rust, docs
				 */
				tags: () => LocalizedString
				/**
				 * book, rustbook
				 */
				aliases: () => LocalizedString
			}
			defaultActionOptions: {
				/**
				 * Auto
				 */
				auto: () => LocalizedString
				/**
				 * Command
				 */
				command: () => LocalizedString
				/**
				 * URL
				 */
				url: () => LocalizedString
			}
		}
	}
	markdownPreview: {
		/**
		 * Copied code block #{index}
		 */
		copiedCodeBlock: (arg: { index: unknown }) => LocalizedString
		/**
		 * Code block #{index} not found
		 */
		codeBlockNotFound: (arg: { index: unknown }) => LocalizedString
		/**
		 * Failed to copy code block: {error}
		 */
		copyCodeBlockFailed: (arg: { error: unknown }) => LocalizedString
		/**
		 * Source file not found
		 */
		sourceFileNotFound: () => LocalizedString
		/**
		 * Task not found
		 */
		taskNotFound: () => LocalizedString
		/**
		 * Failed to update task: {error}
		 */
		updateTaskFailed: (arg: { error: unknown }) => LocalizedString
	}
	tagCloudPage: {
		/**
		 * Tag Cloud
		 */
		title: () => LocalizedString
		/**
		 * {count} tags
		 */
		tags: (arg: { count: unknown }) => LocalizedString
		/**
		 * {count} tag assignments
		 */
		tagAssignments: (arg: { count: unknown }) => LocalizedString
		/**
		 * Sort by name
		 */
		sortByName: () => LocalizedString
		/**
		 * Sort by count
		 */
		sortByCount: () => LocalizedString
		/**
		 * Filter tags
		 */
		filterPlaceholder: () => LocalizedString
		/**
		 * Failed to load tags: {error}
		 */
		loadError: (arg: { error: unknown }) => LocalizedString
		/**
		 * Search #{tag}
		 */
		searchTag: (arg: { tag: unknown }) => LocalizedString
		/**
		 * No tags found.
		 */
		empty: () => LocalizedString
	}
}

export type Formatters = {}
